### ISSUE TITLE
os03b10.yaml  ERROR 

### ISSUE THREAD

**Issue by scsmt** [OpenIPC/firmware#1037]
os03b10.yaml file with in path general/package/ingenic-osdrv-t31/files/sensor/os03b10.yaml has a EDIT error 
 the value  below should be " width: 2304 " 
sensor:
  name: os03b10
  address: 0x3c
  width: 2034            <------------------
  height: 1296
  bus: i2c
 
this error will cause the T31X With Sensor os03b10 not work, 

ERROR IS: 
      Majestic crash and exit.
-----------------------------
09:42:33  <       majestic> [     sdk] imp_system_init@438           ImpSystemInit success
09:42:33  <       majestic> [     sdk] imp_framesource_init@488      IMP_FrameSource_CreateChn(chn0) error !
09:42:33  <       majestic> [     sdk] start_sdk@1355                FrameSource init failed
09:42:33  <       majestic> [    main] main@209                      Shutdown main thread

**Comment by themactep** [comment]
Patch created, PR is pending. Thank you for reporting.
