### ISSUE TITLE
Dihoom WiFi camera

### ISSUE THREAD

**Issue by victor7376** [OpenIPC/firmware#1099]
Hi,  I stumbled across this project as I was looking for a possible alternative firmware for my wifi battery camera.

https://www.amazon.co.uk/dp/B0BGL77HY6

it uses a Ingenic T31 - 290322621B20-ZL

**Comment by themactep** [comment]
It is a battery powered camera with Zeratul bootloader. Despite having a supported T31 processor, the bootloader and MCU-driven enery saving things make this cameras not supported, at least for now.
