### ISSUE TITLE
Working firmware for Anyka v200?

### ISSUE THREAD

**Issue by blackPantherOS** [OpenIPC/firmware#1104]
Hello,
I looking for alternate tested firmware for Anyka V200. I would like to RTSP stream and more privacy :)

This device arrived today... The opened ports
ftp 21/tcp (root login works :( )
port 6789/tcp

The boot log from messages:
[messages.txt](https://github.com/OpenIPC/firmware/files/13254175/messages.txt)

**Comment by viktorxda** [comment]
Support for these devices are currently very unlikely, except an volunteer steps in to create a basic foundation.
