### ISSUE TITLE
Suggestion to add 'usb device mode' to SSC338Q, to act as a usb camera. enhancement

### ISSUE THREAD

**Issue by Raduq91** [OpenIPC/firmware#1128]
Suggestion to add 'usb device mode' to SSC338Q, to act as a usb camera.(currently the usb port is used to connect wifi module, if wifi is also needed, maybe a router configured as client connected to the ethernet port can be used )
```
In the SSC338Q datasheet there is this:
USB Interface
 One USB 2.0 configurable host or device
− Host mode supports EHCI specification
− Device mode supports up to 8 endpoints
```
and
```
1. CHIP OVERVIEW
The SSC338D/SSC338Q series products are highly integrated multimedia System-on-Chip (SoC) products for
high-resolution intelligent video recording applications like IP camera, CAR camera, and USB camera.(usb camera)
```

A video example of a soc with a mipi sensor as a usb webcam, "The tiny UNIX server inside a cheap webcam from Amazon!":
https://youtu.be/Ux8Jd2C9RCQ?t=619

Maybe this is some relevant info:
https://www.reddit.com/r/SteamDeck/comments/10rifa4/made_a_script_to_share_the_decks_internet/  (script in post)
"In order for the script to actually work, you'd have to enable USB Dual-Role Device in the BIOS settings, so that the Deck can act as a USB device instead of a USB host."

To be used as a cheap usb high resolution and or high fps(low latency) camera for different purposes(microscope, webcam, video recorder, motion tracking, etc). I see that there are good mipi sensors available like IMX415(8MP 1920x1080@90fps; 1280x720@120fps); ov4689(datasheet: 4MP ; 2688x1520 90 fps; 1280x720 180 fps; 1920x1080 120 fps; 672x380 330 fps)
I saw videos and posts with the IMX415.
I did not saw videos or posts with OV4689, I do see this: https://github.com/OpenIPC/firmware/blob/d844676bba5d7969af034d7904b2d5b32ec1c591/general/package/ingenic-osdrv-t40/files/sensor/ov4689.yaml

**Comment by viktorxda** [comment]
This is very unlikely to happen, the supported cameras are for the sole purpose to act as stand-alone surveillance devices with the usb port intended for wifi.
