### ISSUE TITLE
SSC30KQ NAND Flash support

### ISSUE THREAD

**Issue by BlackStump** [OpenIPC/firmware#1131]
Is there support for this module?
[S51-P 5MP Dual light WDR Module.pdf](https://github.com/OpenIPC/firmware/files/13323355/S51-P.5MP.Dual.light.WDR.Module.pdf)

**Comment by viktorxda** [comment]
We have support for SSC338Q nand, which is overall very similar and even partially identical.
Chances are high that the linked module is working with mentioned ssc338q-nand firmware.

**Comment by BlackStump** [comment]
Thanks I will see if I can get it flashed

**Comment by viktorxda** [comment]
Closed for now, if you need further support please report back.
