### ISSUE TITLE
newer LTS buildroot version 2023.02.7

### ISSUE THREAD

**Issue by zerog2k** [OpenIPC/firmware#1144]
currently openipc using buildroot-2023.02.1

`https://www.buildroot.org/downloads/buildroot-2023.02.7.tar.gz`

changelog: https://gitlab.com/buildroot.org/buildroot/-/blob/2023.02.7/CHANGES?ref_type=tags#L1-204

**Comment by widgetii** [comment]
Don't open issue, open a PR instead

**Comment by zerog2k** [comment]
#1145
