### ISSUE TITLE
ssc338q imx415, 2.3.11.29, 1080@60 bad video quality

### ISSUE THREAD

**Issue by Raduq91** [OpenIPC/firmware#1179]
h265(same with h264)
.video0.bitrate: 40000
.video0.gopSize: 20
.video0.rcMode: avbr
Used RTSP with VLC(win) Full screen on 1080 monitor to take screenshots
I used frame rate 60 in openipc(resolution and crop fields are empty, vlc shows 1920x1080):
![z1_1080_arrows](https://github.com/OpenIPC/firmware/assets/31180871/88188072-3fe6-4175-993e-9016e60dc005)
I drew small red arrows pointing to bad aliasing.
That Image does not look like 1080p quality and has bigger field of view than the native resolution(native resolution as when using 30 as framerate, vlc shows 3040x2040)

I used frame rate 30 in openipc(resolution and crop fields are empty, vlc shows 3040x2040):
![z1_full](https://github.com/OpenIPC/firmware/assets/31180871/c948d04b-4d75-4083-bd7c-a25881ee3275)

I used frame rate 30 and crop 0x0x1600x1080 in openipc(resolution field empty, vlc shows 1600x1088):
![z1_crop](https://github.com/OpenIPC/firmware/assets/31180871/ac86454f-2cf7-4646-83fa-7e3079e62c13)

I used frame rate 30 and resolution 1920x1080(crop field empty, vlc shows 1920x1080):
![1080_30](https://github.com/OpenIPC/firmware/assets/31180871/0a527bf0-a169-40b8-b83c-df04e521aea1)
This looks more decent, to mention that it looks like it has same aspect ratio as native resolution(not 16:9) so it appears stretched.

**Comment by Raduq91** [comment]
> An update was issued for the driver, please try the following resolutions with the new update:
> 
>     * 3840x2160 at 20fps
> 
>     * 1920x1080 at 20fps
> 
>     * 1920x1080 at 60fps
> 
> 
> Crop basically just cuts a part of the full output picture.

ssc338q (infinity6e family), imx415, 16 MB nor flash, 2.3.12.04-lite, openipc-ssc338q

Still the same issue:
1920x1080@60:
![1080_60_upd](https://github.com/OpenIPC/firmware/assets/31180871/a833ee85-ffae-4eef-9db7-67ec209f4541)

1920x1080@20:
![1080_20_upd](https://github.com/OpenIPC/firmware/assets/31180871/d180aa49-2cf6-4cab-a57e-9906b8825a0b)

( updated with tftp, updating from openipc firmware did not work, it rebooted and it was same firmware)
```
Upgrading firmware
DO NOT CLOSE, REFRESH, OR NAVIGATE AWAY FROM THIS PAGE UNTIL THE PROCESS IS FINISHED!
# /usr/sbin/sysupgrade -k -r -x
[root@openipc-ssc338q /tmp]# /usr/sbin/sysupgrade -k -r -x

OpenIPC System Updater v1.0.21

Vendor	sigmastar
SoC	ssc338q
Kernel	15:18:44 2023-11-29
RootFS	master+456454e, 2023-11-29

Synchronizing time
ntpd: setting time to 2023-12-04 02:17:32.903650 (offset +385127.563953s)
Mon Dec  4 02:17:32 GMT 2023

Checking for sysupgrade update...
A new version is available, trying to activate updated script...
Done. Restarting...

OpenIPC System Updater v1.0.23

Vendor	sigmastar
SoC	ssc338q
Kernel	15:18:44 2023-11-29
RootFS	master+456454e, 2023-11-29

Synchronizing time
ntpd: setting time to 2023-12-04 02:17:34.476844 (offset +385129.240708s)
Mon Dec  4 02:17:34 GMT 2023

Checking for sysupgrade update...
Same version. No update required.

Stop services, sync files, free up memory

--- finished ---
```

**Comment by viktorxda** [comment]
Try to clean the overlay together with force_ver:
`sysupgrade -k -r -n --force_ver`

Also please provide some pictures takes from the webui:
`http://192.168.1.15/image.jpg`

**Comment by Raduq91** [comment]
> Try to clean the overlay together with force_ver: `sysupgrade -k -r -n --force_ver`
> 
> Also please provide some pictures taken with the webui: `http://192.168.1.15/image.jpg`
(the log from the previous comment was from the page: http://192.168.1.15/cgi-bin/firmware.cgi)


1920x1080@60 from http://192.168.1.15/image.jpg:
![image_1080_60](https://github.com/OpenIPC/firmware/assets/31180871/8166c18f-1ada-4659-98ca-01e914f77ad1)

1920x1080@20 from http://192.168.1.15/image.jpg:
![image_1080_20](https://github.com/OpenIPC/firmware/assets/31180871/898a0588-317b-42f5-87bb-aa12d4332db6)

**Comment by themactep** [comment]
Looks like you were trying to update from port 80 which is wrong as our web ui port is 85.

**Comment by viktorxda** [comment]
I think we basically have two problems:
- The sensor resolution is binned to 1920x1080 to allow the usage of up to 1080p@90fps.
- The calibration file might also come into play by oversharpening the picture.

The intended resolution is 3840x2160@20fps, this is the maximum what the interface and encoder can handle.
If the picture is set to 1080p@20fps the internal scaler will be used (4k sensor -> 1080p encoder) to resize the picture, which results in a better quality.
Everything above 20fps will use the sensor binning mode, so the sensor and encoder will use 1080p without rescaling.

**Comment by Raduq91** [comment]
Here is a link with 12 images. Slightly 3 different focus distances, using 'sensor configuration file' IMX415 and IMX335 at 1080@20FPS and 1080@60FPS:
https://www.dropbox.com/scl/fi/5hx2m9fwm9ynjhnand3ix/images.zip?rlkey=wmyiitydv0k9cd1x8v4iuozqa&dl=0

**Comment by Raduq91** [comment]
> Here is the sensor calibration tool, you can try to adjust the quality this way:
> 
>     * [Download SSCamIQTool](https://github.com/viktorxda/SSCamIQTool/releases)
> 
> 
> With the newest firmware you can directly connect to this tool:
> 
>     * Enable the iqserver on the camera:
>       `cli -s .isp.iqServer true`
> 
>     * Start SSCamIQTool.exe, enter the Camera IP and click the connect button.

Are changes permanent in the sense that they are not lost after openipc reset/reflash? I did not made a backup.

**Comment by viktorxda** [comment]
You need save your changes to a new calibration file.
This file can be uploaded to the camera and then used as new default.

**Comment by Raduq91** [comment]
(Can "Commits on Dec 5, 2023" "Sigmastar: update imx415 sensor" be reversed, or part of it so the '20fps > '30fps'?)
I modified some Sharpness settings:
1080_90fps default sharpness:
![1080_90fps](https://github.com/OpenIPC/firmware/assets/31180871/d6561b2e-3332-4d88-8882-d921cadc125f)

1080_90fps_custom_sharpness:
![1080_90fps_custom_sharpness](https://github.com/OpenIPC/firmware/assets/31180871/9c7f63a6-58ea-4b4f-9be8-ae6c83c7dcba)






How to upload and what file to upload to use as default?

**Comment by viktorxda** [comment]
Copy it to the `/etc/sensors` directory on the camera.
You can then select the profile in the isp menu on the camera website

**Comment by tipoman9** [comment]
![Binning_vs_native_mode](https://github.com/OpenIPC/firmware/assets/97629810/cfae66c9-c062-420d-9bbf-11c7736eef88)
Another comparison. imx415.
3840x2160 native vs 1920x1080 binning.
Same camera position, the image is scaled down on the ground, since the screen is 1080p.
Will try to finetune with SSCamIQTool

**Comment by viktorxda** [comment]
A new setting was added which should fix this issue:
`cli -s .image.sharpness 15`
