### ISSUE TITLE
How does musl work with uClibc?

### ISSUE THREAD

**Issue by northyzq** [OpenIPC/firmware#1189]
When I was using hi3516ev300, I found that the file system uses musl library, but HiSilicon provides shared library was uclib library. I would like to ask how these two c libraries work together?

As shown below, libmpi.so is used in majestic. When using ldd to view libmpi.so, an error will be reported and some symbols cannot be found.

In the /lib directory, I only found that ld-uClibc.so.0 & ld-musl-arm.so.1 exist at the same time and are linked to libc.so at the same time. No other processing was found.

How do the uclib provided by HiSilicon SDK and the musl used in the program coexist?

In addition, I have verified that programs compiled directly using the tool chain provided by HiSilicon SDK cannot be run in the current hi3516ev300 musl environment, and a uclib_main error will be prompted. Even if I compile a test uclib library by myself and use the openipc musl tool chain compiler to link my own uclib library, it still cannot run normally, which means that they are binary incompatible.

I am very confused about how openipc is implemented. Please give me some advice. thanks.

```
root@openipc-hi3516ev300:/usr/bin# ldd majestic 
    /lib/ld-musl-arm.so.1 (0x7f56a000)
    libmpi.so => /usr/lib/libmpi.so (0xb6ef6000)
    lib_hiae.so => /usr/lib/lib_hiae.so (0xb6ead000)
    libisp.so => /usr/lib/libisp.so (0xb6e2d000)
    libive.so => /usr/lib/libive.so (0xb6e01000)
    lib_hidehaze.so => /usr/lib/lib_hidehaze.so (0xb6de9000)
    lib_hidrc.so => /usr/lib/lib_hidrc.so (0xb6dce000)


root@openipc-hi3516ev300:/usr/bin# ldd ../lib/libmpi.so 
    ldd (0x7f563000)
    libdl.so.0 => ldd (0x7f563000)
    libc.so.0 => ldd (0x7f563000)
Error relocating ../lib/libmpi.so: HI_VOICE_EncReset: symbol not found
Error relocating ../lib/libmpi.so: strncpy_s: symbol not found
Error relocating ../lib/libmpi.so: HI_UPVQE_Create: symbol not found
Error relocating ../lib/libmpi.so: HI_DNVQE_ReadFrame: symbol not found
Error relocating ../lib/libmpi.so: HI_UPVQE_Destroy: symbol not found
Error relocating ../lib/libmpi.so: HI_DNVQE_Destroy: symbol not found
Error relocating ../lib/libmpi.so: HI_VOICE_EncodeFrame: symbol not found
Error relocating ../lib/libmpi.so: snprintf_s: symbol not found
Error relocating ../lib/libmpi.so: memcpy_s: symbol not found
Error relocating ../lib/libmpi.so: memset_s: symbol not found
Error relocating ../lib/libmpi.so: HI_VOICE_DecodeFrame: symbol not found
Error relocating ../lib/libmpi.so: memmove_s: symbol not found

 
 root@openipc-hi3516ev300:/lib# ls -l
total 644
drwxr-xr-x    4 root     root           368 Jun 13 14:41 firmware
lrwxrwxrwx    1 root     root             7 Jun 13 14:26 ld-musl-arm.so.1 -> libc.so
lrwxrwxrwx    1 root     root            12 Jun 13 14:42 ld-uClibc.so.0 -> /lib/libc.so
lrwxrwxrwx    1 root     root            18 Jun 13 14:26 libatomic.so.1 -> libatomic.so.1.2.0
-rwxr-xr-x    1 root     root         13512 Jun 13 14:42 libatomic.so.1.2.0
-rwxr-xr-x    1 root     root        534088 Jun 13 14:42 libc.so
-rwxr-xr-x    1 root     root        103908 Jun 13 14:42 libgcc_s.so.1
drwxr-xr-x    2 root     root           232 Jun 13 14:24 mdev
```

**Comment by widgetii** [comment]
There is not too much difference like different `mmap` function signature https://github.com/OpenIPC/mini/blob/master/src/videohw.c#L1248

or some uclibc functions implemented as stubs https://github.com/OpenIPC/gkrcparams/blob/master/gkrcparams.c#L150

**Comment by northyzq** [comment]
> There is not too much difference like different `mmap` function signature

That's cool, I'll try it too.
