### ISSUE TITLE
Степень важности обновлений модулей прошивки

### ISSUE THREAD

**Issue by cronyx** [OpenIPC/firmware#120]
Необходима возможность видеть степень важности для обновления модулей прошивки. Так как есть вероятность выпуска обновлений безопасности, юзер, глядя в интерфейс должен понимать что обновление обязательно к установке или на него можно забить, по принципу - работает и не трогай.

**Comment by themactep** [comment]
Юзер сам решает, надо ему обновлять прошивку или нет. У нас сейчас нет других возможностей обратной связи, кроме как через участие в тележных чатах и мониторинга изменений через описания коммитов. Даже если сделать в веб интерфейсе страницу с новостями, подтягиваемыми извне, нужен кто-то, кто будет их писать. Пока я таких желающих не вижу. Да и не все камеры имеют доступ к внешней сети.

Посему предлагаю коцнуть это тикет.
