### ISSUE TITLE
25q64 nor spi capacity insufficient?

### ISSUE THREAD

**Issue by kangz543g** [OpenIPC/firmware#1213]
root@openipc-t21:/rom/lib/modules/3.10.14__isvp_turkey_1.0__/ingenic# rm  sensor_ov2735b_t21z.ko
rm: remove 'sensor_ov2735b_t21z.ko'? yes
rm: can't remove 'sensor_ov2735b_t21z.ko': Read-only file system
It cannot be deleted.

sensor_ov2735b_t21z.ko
sensor_sc2232_t21n.ko   
sensor_sc2300_t21z.ko   
sensor_sc2335_t21n.ko
sensor_sc2335_t21z.ko
removal???

**Comment by viktorxda** [comment]
Merged with #1209
