### ISSUE TITLE
GK7205V300 + sc223a_4l for FPV (Wifi injection problem)

### ISSUE THREAD

**Issue by Schildkroet** [OpenIPC/firmware#1273]
Hello,

i have a GK7205V300 + sc5239p (detected as 223a). When i flash "Ultimate" FW, the camera works, if i set config "/etc/sensors/4l_sc223a_i2c_1080p.ini".
When i flash "FPV" FW, it doesn't work, because the driver seems to be not included.

Would it be possible to add the driver to V300 like it is done here?
https://github.com/OpenIPC/firmware/commit/dcb99dc3aec422c286e7ea577ca7e6b8c7047df7

**Comment by RoboSchmied** [comment]
The installation of sensor drivers is described [here](https://github.com/OpenIPC/wiki/blob/master/en/firmware-sensor-install-sc223a.md).

**Comment by Schildkroet** [comment]
But there are no files for my specific SoC.
Using other files broke my system

**Comment by RoboSchmied** [comment]
v300 uses the same sensor files as [v200](https://github.com/OpenIPC/firmware/tree/master/general/package/goke-osdrv-gk7205v200/files/sensor). 
Please show the output of majestic (fpv).

**Comment by Schildkroet** [comment]
How to show output of majestic?

**Comment by RoboSchmied** [comment]
ssh to cam 
```
killall majestic
majestic
```

**Comment by Schildkroet** [comment]
Original System:
![image](https://github.com/OpenIPC/firmware/assets/29074960/11492e96-283f-4ecd-9c87-00aa2b1bb7a3)

After installing libs:
![image](https://github.com/OpenIPC/firmware/assets/29074960/deb44cbf-f337-47e5-8c1a-f524203e582a)

At least my system didnt crash this time, but i still get no output

**Comment by RoboSchmied** [comment]
Thank you. Please compare your "Isp_FrameRate" in file /etc/sensors/sc223a_i2c_1080p.ini  with your video0.fps in /etc/majestic.yaml.

Or show me both files.

**Comment by Schildkroet** [comment]
Both are set to 30fps

**Comment by RoboSchmied** [comment]
please try setting them to 25 fps

**Comment by Schildkroet** [comment]
Both are set to 25:
![image](https://github.com/OpenIPC/firmware/assets/29074960/c687c53a-f20e-4c5f-8bdb-1c6477e77be3)

**Comment by RoboSchmied** [comment]
You said it worked on ultimate using the 4l driver.  (4l_sc223a_i2c_1080p.ini and [libsns_sc223a_4l.so](https://github.com/OpenIPC/firmware/raw/master/general/package/goke-osdrv-gk7205v200/files/sensor/libsns_sc223a_4l.so))
You should try them.

delete the other sc223a files before

**Comment by Schildkroet** [comment]
No, still not working (same behaviour)

**Comment by RoboSchmied** [comment]
Please show your /etc/majestic.yaml.

**Comment by Schildkroet** [comment]
```
system:
  webAdmin: disabled
  buffer: 1024
image:
  mirror: false
  flip: false
  rotate: none
  contrast: 50
  hue: 50
  saturation: 50
  luminance: 50
osd:
  enabled: false
  template: "%d.%m.%Y %H:%M:%S"
nightMode:
  enabled: false
records:
  enabled: false
  path: /mnt/mmcblk0p1/%F/%H.mp4
  maxUsage: 95
video0:
  enabled: true
  size: 1920x1080
  fps: 25
  bitrate: 5120
  codec: h264
  rcMode: cbr
  gopSize: 1.5
video1:
  enabled: false
jpeg:
  enabled: false
mjpeg:
  size: 640x360
  fps: 5
  bitrate: 1024
audio:
  enabled: false
  volume: auto
  srate: 8000
rtsp:
  enabled: true
  port: 554
hls:
  enabled: false
youtube:
  enabled: false
motionDetect:
  enabled: false
  visualize: false
  debug: false
ipeye:
  enabled: false
watchdog:
  enabled: true
  timeout: 300
isp:
 sensorConfig: /etc/sensors/4l_sc223a_i2c_1080p.ini
 slowShutter: disabled
netip:
  enabled: false
outgoing:
  enabled: true
  server: udp://127.0.0.1:5600

```

**Comment by RoboSchmied** [comment]
Remove (or comment out) everything in the video0 section but not "enabled: true".

**Comment by Schildkroet** [comment]
Still same Timeout error

**Comment by RoboSchmied** [comment]
Please try the sc223a (not 4l) drivers again with those majestic settings.

You should be able to find the working files (.ini and .so and majestic.yaml) in your ultimate image.

**Comment by Schildkroet** [comment]
This is the working output on Ultimate:
![image](https://github.com/OpenIPC/firmware/assets/29074960/473d2c17-06ea-4d46-9707-cb4f49fee9c8)

Is this helpful?

**Comment by Schildkroet** [comment]
I set up my fpv image again with ultimate settings, but now i get this error:
![image](https://github.com/OpenIPC/firmware/assets/29074960/9875c552-6d27-478e-8766-62b948fef472)

**Comment by Schildkroet** [comment]
So i have either a working wifi or camera

Problem seems to be somewhere with mipi
`[mipi]
lane_id = 0|1|-1|-1|-1|-1|-1|-1|      ;lane_id: -1 - disable`

if you change the first "1" to 2 (like in other config), wifi works, but not camera...

**Comment by Schildkroet** [comment]
This driver doesn't work (Timeout error as shown before). I have to use 4l

**Comment by Schildkroet** [comment]
It seems to cause problems with wifibroadcast. Wifi driver is loaded and i can start wifibroadcast. But as soon as i start majestetic, wifibroadcast reports a socket error.
![image](https://github.com/OpenIPC/firmware/assets/29074960/3a5d2f64-efdb-4c8d-b937-e58c349ba5cb)

**Comment by RoboSchmied** [comment]
This is a new issue. (maybe injection capable drivers are not in the fpv image)
Please post your majestic.yaml video0 part that solved the sensor problem.

Thank you

**Comment by Schildkroet** [comment]
It seems majestic is crashing wifibroadcast when connecting. If i change port 5600 to something else (only in 1 config), i still get the connection refused, but at least nothing is crashing.

**Comment by Schildkroet** [comment]
```
system:
  webAdmin: enabled
  buffer: 1024
image:
  mirror: false
  flip: false
  rotate: none
  contrast: 50
  hue: 50
  saturation: 50
  luminance: 50
osd:
  enabled: false
  template: "%d.%m.%Y %H:%M:%S"
nightMode:
  enabled: false
records:
  enabled: false
  path: /mnt/mmcblk0p1/%F/%H.mp4
  maxUsage: 95
video0:
  enabled: true
  crop: 0x0x1280x720
video1:
  enabled: false
jpeg:
  enabled: false
mjpeg:
  size: 640x360
  fps: 5
  bitrate: 1024
audio:
  enabled: false
  volume: auto
  srate: 8000
rtsp:
  enabled: true
  port: 554
hls:
  enabled: false
youtube:
  enabled: false
motionDetect:
  enabled: false
  visualize: false
  debug: false
ipeye:
  enabled: false
watchdog:
  enabled: true
  timeout: 300
isp:
  slowShutter: disabled
  sensorConfig: /etc/sensors/4l_sc223a_i2c_1080p.ini
netip:
  enabled: false
outgoing:
  enabled: true
  server: udp://127.0.0.1:5600
```

**Comment by Schildkroet** [comment]
Wifi:
```
usb 1-1: ath9k_htc: Firmware ath9k_htc/htc_9271-1.4.0.fw requested
usbcore: registered new interface driver ath9k_htc
usb 1-1: ath9k_htc: Transferred FW: ath9k_htc/htc_9271-1.4.0.fw, size: 51008
ath9k_htc 1-1:1.0: ath9k_htc: HTC initialized with 33 credits
ath9k_htc 1-1:1.0: ath9k_htc: FW Version: 1.4
ath9k_htc 1-1:1.0: FW RMW support: On
ath: EEPROM regdomain: 0x0
ath: EEPROM indicates default country code should be used
ath: doing EEPROM country->regdmn map search
ath: country maps to regdmn code: 0x3a
ath: Country alpha2 being used: US
ath: Regpair used: 0x3a
ieee80211 phy0: Atheros AR9271 Rev:1
ATH: TX Power set: 20
ATH: TX Power set: 20
ATH: TX Power set: 20
ATH: TX Power set: 20
ATH: TX Power set: 20
device wlan0 entered promiscuous mode
usb 1-1: USB disconnect, device number 2
usb 1-1: ath9k_htc: USB layer deinitialized
usb 1-1: new high-speed USB device number 3 using xhci-hcd
usb 1-1: ath9k_htc: Firmware ath9k_htc/htc_9271-1.4.0.fw requested
usb 1-1: ath9k_htc: Transferred FW: ath9k_htc/htc_9271-1.4.0.fw, size: 51008
ath9k_htc 1-1:1.0: ath9k_htc: HTC initialized with 33 credits
ath9k_htc 1-1:1.0: ath9k_htc: FW Version: 1.4
ath9k_htc 1-1:1.0: FW RMW support: On
ath: EEPROM regdomain: 0x0
ath: EEPROM indicates default country code should be used
ath: doing EEPROM country->regdmn map search
ath: country maps to regdmn code: 0x3a
ath: Country alpha2 being used: US
ath: Regpair used: 0x3a
ieee80211 phy1: Atheros AR9271 Rev:1
```

**Comment by Schildkroet** [comment]
Turns out the injection problem was a power supply issue.
Everything seems to work now.
Thanks for the help
