### ISSUE TITLE
jco h42 module cpu ingenic T31n，sensor jxq03，no video。

### ISSUE THREAD

**Issue by catulacnpoly** [OpenIPC/firmware#1325]
the module is jco h42 the cpu is ingenic t31n，cmos sensor is jxq03，at the first I try to flash it use the openipc official mothed，but failed，then I flash it use a ch341 programmer to do it well，it can boot the openipc_lite,but sadly,I got no video out at preview page,it seems jxq03 works well,and majestic works well too,someone tell me what the reason?

I copy the screen to youtube：https://youtu.be/0ePk9cPmWaU

boot info
<img width="633" alt="t31" src="https://github.com/OpenIPC/firmware/assets/161186597/12963fb0-ec4a-49d6-8b80-1964c153705c">

U-Boot SPL 2013.07-g05f0cca (Oct 10 2023 - 00:04:03)
Timer init
CLK stop
PLL init
pll_init:366
pll_cfg.pdiv = 10, pll_cfg.h2div = 5, pll_cfg.h0div = 5, pll_cfg.cdiv = 1, pll_c                                                                             fg.l2div = 2
nf=118 nr = 1 od0 = 1 od1 = 2
cppcr is 07605100
CPM_CPAPCR 0750510d
nf=84 nr = 1 od0 = 1 od1 = 2
cppcr is 05405100
CPM_CPMPCR 07d0590d
nf=100 nr = 1 od0 = 1 od1 = 2
cppcr is 06405100
CPM_CPVPCR 0640510d
cppcr 0x9a773310
apll_freq 1404000000
mpll_freq 1000000000
vpll_freq = 1200000000
ddr sel mpll, cpu sel apll
ddrfreq 500000000
cclk  1404000000
l2clk 702000000
h0clk 200000000
h2clk 200000000
pclk  100000000
CLK init
SDRAM init
sdram init start
ddr_inno_phy_init ..!
phy reg = 0x00000007, CL = 0x00000007
ddr_inno_phy_init ..! 11:  00000004
ddr_inno_phy_init ..! 22:  00000006
ddr_inno_phy_init ..! 33:  00000006
REG_DDR_LMR: 00000210
REG_DDR_LMR: 00000310
REG_DDR_LMR: 00000110
REG_DDR_LMR, MR0: 00f73011
T31_0x5: 00000007
T31_0x15: 0000000c
T31_0x4: 00000000
T31_0x14: 00000002
INNO_TRAINING_CTRL 1: 00000000
INNO_TRAINING_CTRL 2: 000000a1
T31_cc: 00000003
INNO_TRAINING_CTRL 3: 000000a0
T31_118: 0000003c
T31_158: 0000003c
T31_190: 00000021
T31_194: 0000001f
jz-04 :  0x00000051
jz-08 :  0x000000a0
jz-28 :  0x00000024
DDR PHY init OK
INNO_DQ_WIDTH   :00000003
INNO_PLL_FBDIV  :00000014
INNO_PLL_PDIV   :00000005
INNO_MEM_CFG    :00000051
INNO_PLL_CTRL   :00000018
INNO_CHANNEL_EN :0000000d
INNO_CWL        :00000006
INNO_CL         :00000007
DDR Controller init
DDRC_STATUS         0x80000001
DDRC_CFG            0x0a288a40
DDRC_CTRL           0x0000011c
DDRC_LMR            0x00400008
DDRC_DLP            0x00000000
DDRC_TIMING1        0x040e0806
DDRC_TIMING2        0x02170707
DDRC_TIMING3        0x2007051e
DDRC_TIMING4        0x1a240031
DDRC_TIMING5        0xff060405
DDRC_TIMING6        0x32170505
DDRC_REFCNT         0x00f26901
DDRC_MMAP0          0x000020fc
DDRC_MMAP1          0x00002400
DDRC_REMAP1         0x03020d0c
DDRC_REMAP2         0x07060504
DDRC_REMAP3         0x0b0a0908
DDRC_REMAP4         0x0f0e0100
DDRC_REMAP5         0x13121110
DDRC_AUTOSR_EN      0x00000000
sdram init finished
SDRAM init ok
board_init_r
image entry point: 0x80100000

U-Boot 2013.07-g05f0cca (Oct 10 2023 - 00:04:03)

Board: ISVP (Ingenic XBurst T31 SoC)
DRAM:  64 MiB
Top of RAM usable for U-Boot at: 84000000
Reserving 476k for U-Boot at: 83f88000
Reserving 32832k for malloc() at: 81f78000
Reserving 32 Bytes for Board Info at: 81f77fe0
Reserving 124 Bytes for Global Data at: 81f77f64
Reserving 256k for boot params() at: 81f37f64
Stack Pointer at: 81f37f48
Now running in RAM - U-Boot at: 83f88000
MMC:   msc: 0
the manufacturer 1c
SF: Detected EN25QH64

*** Warning - bad CRC, using default environment

Saving default environment...
Erasing SPI flash...Writing to SPI flash...done
In:    serial
Out:   serial
Err:   serial
gpio_request[hichip_mmc_enable] = 62
Net:   ====>phy 0:0x0-0x128 found
SPEED:2, DUPLEX:2
Jz4775-9161
Autoupdate...
Card did not respond to voltage select!
Press Ctrl-c to abort autoboot... 1
the manufacturer 1c
SF: Detected EN25QH64

--->probe spend 4 ms
SF: 3145728 bytes @ 0x50000 Read: OK
--->read spend 1010 ms
## Booting kernel from Legacy Image at 80600000 ...
   Image Name:   Linux-3.10.14__isvp_swan_1.0__-t
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    1879957 Bytes = 1.8 MiB
   Load Address: 80010000
   Entry Point:  803fe550
   Verifying Checksum ... OK
   Uncompressing Kernel Image ... OK

Starting kernel ...

[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.10.14__isvp_swan_1.0__ (runner@fv-az665-591) (bui                                                                             ldroot-gcc-12.3.0) #2 PREEMPT Tue Feb 20 13:25:30 UTC 2024
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 RESET ERROR PC:9F3C8F7B
[    0.000000] CPU0 revision is: 00d00100 (Ingenic Xburst)
[    0.000000] FPU revision is: 00b70000
[    0.000000] CCLK:1404MHz L2CLK:702Mhz H0CLK:250MHz H2CLK:250Mhz PCLK:125Mhz
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 0055e000 @ 00010000 (usable)
[    0.000000]  memory: 00032000 @ 0056e000 (usable after init)
[    0.000000] User-defined physical RAM map:
[    0.000000]  memory: 02800000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x00000000-0x027fffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x00000000-0x027fffff]
[    0.000000] Primary instruction cache 32kB, 8-way, VIPT, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 8-way, VIPT, no aliases, linesize 32 byt                                                                             es
[    0.000000] pls check processor_id[0x00d00100],sc_jz not support!
[    0.000000] MIPS secondary cache 128kB, 8-way, linesize 32 bytes.
[    0.000000] Built 1 zonelists in Zone order, mobility grouping off.  Total pa                                                                             ges: 10160
[    0.000000] Kernel command line: mem=40M rmem=24M@0x2800000 console=ttyS1,115                                                                             200n8 panic=20 root=/dev/mtdblock3 rootfstype=squashfs init=/init mtdparts=jz_sf                                                                             c:256k(boot),64k(env),2048k(kernel),5120k(rootfs),-(rootfs_data)
[    0.000000] PID hash table entries: 256 (order: -2, 1024 bytes)
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Memory: 34192k/40960k available (4076k kernel code, 6768k reserve                                                                             d, 1417k data, 200k init, 0k highmem)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000] NR_IRQS:358
[    0.000000] clockevents_config_and_register success.
[    0.000014] Calibrating delay loop... 1397.55 BogoMIPS (lpj=6987776)
[    0.037792] pid_max: default: 32768 minimum: 301
[    0.042652] Mount-cache hash table entries: 512
[    0.047580] Initializing cgroup subsys debug
[    0.051838] Initializing cgroup subsys freezer
[    0.057918] devtmpfs: initialized
[    0.062728] regulator-dummy: no parameters
[    0.067114] NET: Registered protocol family 16
[    0.074858] Skipping MSC1_PB GPIO setup
[    0.078742] Skipping WYZE GPIO setup
[    0.082286] Skipping WYZE GPIO setup
[    0.105418] bio: create slab <bio-0> at 0
[    0.115553] jz-dma jz-dma: JZ SoC DMA initialized
[    0.121431] usbcore: registered new interface driver usbfs
[    0.127866] usbcore: registered new interface driver hub
[    0.133372] usbcore: registered new device driver usb
[    0.139014]  (null): set:311  hold:312 dev=125000000 h=625 l=625
[    0.146926] Switching to clocksource jz_clocksource
[    0.154300] jz-dwc2 jz-dwc2: cgu clk gate get error
[    0.159298] DWC IN OTG MODE
[    0.162844] dwc2 dwc2: Keep PHY ON
[    0.166214] dwc2 dwc2: Using Buffer DMA mode
[    0.170541] dwc2 dwc2: Core Release: 3.00a
[    0.174818] dwc2 dwc2: DesignWare USB2.0 High-Speed Host Controller
[    0.181110] dwc2 dwc2: new USB bus registered, assigned bus number 1
[    0.188732] hub 1-0:1.0: USB hub found
[    0.192580] hub 1-0:1.0: 1 port detected
[    0.196590] dwc2 dwc2: DWC2 Host Initialized
[    0.201132] NET: Registered protocol family 2
[    0.206080] TCP established hash table entries: 512 (order: 0, 4096 bytes)
[    0.213116] TCP bind hash table entries: 512 (order: -1, 2048 bytes)
[    0.219488] TCP: Hash tables configured (established 512 bind 512)
[    0.225818] TCP: reno registered
[    0.229022] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.234974] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.241478] NET: Registered protocol family 1
[    0.246094] RPC: Registered named UNIX socket transport module.
[    0.252088] RPC: Registered udp transport module.
[    0.256789] RPC: Registered tcp transport module.
[    0.261557] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.268724] freq_udelay_jiffys[0].max_num = 10
[    0.273222] cpufreq  udelay  loops_per_jiffy
[    0.277572] dwc2 dwc2: ID PIN CHANGED!
[    0.281399] 12000     59724   59724
[    0.284652] 24000     119449  119449
[    0.288070] 60000     298622  298622
[    0.291513] 120000    597245  597245
[    0.295132] 200000    995409  995409
[    0.298582] 300000    1493114         1493114
[    0.302394] 600000    2986229         2986229
[    0.306023] 792000    3941822         3941822
[    0.309731] 1008000   5016864         5016864
[    0.313562] 1200000   5972458         5972458
[    0.327468] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.334656] jffs2: version 2.2. © 2001-2006 Red Hat, Inc.
[    0.340741] msgmni has been set to 66
[    0.345749] io scheduler noop registered
[    0.349672] io scheduler cfq registered (default)
[    0.361680] jz-uart.1: ttyS1 at MMIO 0x10031000 (irq = 58) is a uart1
[    0.369302] console [ttyS1] enabled, bootconsole disabled
[    0.369302] console [ttyS1] enabled, bootconsole disabled
[    0.389508] brd: module loaded
[    0.397402] loop: module loaded
[    0.400892] logger: created 256K log 'log_main'
[    0.407834] jz TCU driver register completed
[    0.413478] the id code = 1c7017, the flash name is EN25QH64
[    0.419335] JZ SFC Controller for SFC channel 0 driver register
[    0.425662] 5 cmdlinepart partitions found on MTD device jz_sfc
[    0.431783] Creating 5 MTD partitions on "jz_sfc":
[    0.436826] 0x000000000000-0x000000040000 : "boot"
[    0.442886] 0x000000040000-0x000000050000 : "env"
[    0.448848] 0x000000050000-0x000000250000 : "kernel"
[    0.455184] 0x000000250000-0x000000750000 : "rootfs"
[    0.461365] 0x000000750000-0x000000800000 : "rootfs_data"
[    0.468117] SPI NOR MTD LOAD OK
[    0.471592] Bus Mode Reg after reset: 0x00020101, cnt=0
[    0.480416] libphy: jz_mii_bus: probed
[    0.484657] =======>gmacdev = 0x82277380<================
[    0.490240] =========>gmacdev->MacBase = 0xb34b0000 DmaBase = 0xb34b1000
[    0.497295] Bus Mode Reg after reset: 0x00020101, cnt=0
[    0.504423] jz_mac jz_mac.0: JZ on-chip Ethernet MAC driver, Version 1.0
[    0.511572] STA : @@@@@@ rtusb init rt2870 --->
[    0.516502] usbcore: registered new interface driver rt2870
[    0.522508] usbcore: registered new interface driver asix
[    0.528101] i2c /dev entries driver
[    0.533059] wait stable.[289][cgu_msc0]
[    0.537034] jzmmc_v1.2 jzmmc_v1.2.0: vmmc regulator missing
[    0.543204] jzmmc_v1.2 jzmmc_v1.2.0: register success!
[    0.548564] jzmmc_v1.2 jzmmc_v1.2.1: vmmc regulator missing
[    0.554744] jzmmc_v1.2 jzmmc_v1.2.1: register success!
[    0.560546] ipip: IPv4 over IPv4 tunneling driver
[    0.566146] TCP: cubic registered
[    0.570680] NET: Registered protocol family 10
[    0.576221] NET: Registered protocol family 17
[    0.582264] input: gpio-keys as /devices/platform/gpio-keys/input/input0
[    0.589672] drivers/rtc/hctosys.c: unable to open rtc device (rtc0)
[    0.600339] VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
[    0.611352] devtmpfs: mounted
[    0.614858] Freeing unused kernel memory: 200K (8056e000 - 805a0000)
[    1.038338] jffs2: notice: (455) jffs2_build_xattr_subsystem: complete buildi                                                                             ng xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0                                                                              orphan) found.
[    1.054293] jzmmc_v1.2 jzmmc_v1.2.0: card inserted, state=0
Timezone env variable not found, using system default.
Tue Feb 20 13:29:18 GMT 2024
Saving 2048 bits of creditable seed for next boot
Starting syslogd: OK
Starting klogd: OK
Running sysctl: OK
Loading modules:modprobe: module exfat not found in modules.dep
Starting rngd: OK
Customizer script not present...
Starting mdev...
Starting network...
udhcpc: started, v1.36.1
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: no lease, forking to background
Starting ntpd: OK
Starting dropbear sshd: OK
Production mode
Starting httpd: OK
Starting mini-snmpd: DISABLED, OK
Starting telnetd: DISABLED, OK
Starting crond: OK

Loading of kernel modules...
ingenic: Get data from sinfo and set SENSOR as jxq03
ingenic: Write detected jxq03 to U-Boot ENV
--------------------
AVPU_PARAM: clk_name=vpll avpu_clk=400000000
ISP_PARAM: isp_clk=150000000
SENSOR: jxq03
SENSOR_PARAM:
--------------------
Starting telegram-bot.sh: OK
ingenic: Loading video system has started...
Starting majestic: OK

**Comment by cronyx** [comment]
try run this commands via ssh and reboot:

```
cli -s .isp.blkCnt 1
fw_setenv osmem 39M
fw_setenv rmem 25M@0x2700000
```

**Comment by catulacnpoly** [comment]
Thank you cronyx ,I got the video preview.
