### ISSUE TITLE
打不开摄像机的 Web 界面问题

### ISSUE THREAD

**Issue by ljc111111111111111111111111111111** [OpenIPC/firmware#1330]
已经成功烧录OpenIPC固件
![image](https://github.com/OpenIPC/firmware/assets/137600263/5388aca6-ad88-4fda-82e1-73a6098b9ed2)
，但打不开摄像机的 Web 界面
![image](https://github.com/OpenIPC/firmware/assets/137600263/34cd8d3b-b455-4222-b3a9-cb4d31a1d0ee)
，我板子是T31ZX，sensor是GC2063，烧录上OpenIPC后其内sensor默认为GC2053，我不知道是sensor问题还是其他什么问题，如果是sensor问题，我将环境变量从原来GC2053改为GC2063，但打印ipcinfo依旧显示为GC2053，该怎么处理呢？希望大佬帮忙解决

**Comment by ljc111111111111111111111111111111** [comment]
按您给的指令来一直卡住
![image](https://github.com/OpenIPC/firmware/assets/137600263/7acbafe7-9150-45f4-898c-70f334d971b7)
端口换为80也不行
![image](https://github.com/OpenIPC/firmware/assets/137600263/8cdc5895-20d9-4e0e-ae63-a571e44be1d0)

**Comment by cronyx** [comment]
gc2063 = gc2053

**Comment by ljc111111111111111111111111111111** [comment]
已经改回gc2053，也有驱动，
![image](https://github.com/OpenIPC/firmware/assets/137600263/e79a3d49-b29f-431e-ba5e-7137ee0c6fee)
，但还是打不开web界面

**Comment by ljc111111111111111111111111111111** [comment]
![image](https://github.com/OpenIPC/firmware/assets/137600263/dd305781-4d7d-4f2b-b8d9-18d7edf1ce2e)

**Comment by ljc111111111111111111111111111111** [comment]
应该是我还没有联网，OpenIPC有MT7862的WIFI驱动吗？还是说我mt7862的驱动编译进OpenIPC的固件中？
