### ISSUE TITLE
[Firmware] It is necessary to add PWm and WDT modules for the GK7205V300 processor

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/firmware#134]
It is necessary to add PWm and WDT modules for the GK7205V300 processor

**Comment by dimerr** [comment]
Modules are there, we need positive feedback on usage

`modprobe gk7205v200_wdt `
restart majestic and see how it goes

**Comment by cronyx** [comment]
PR #141

**Comment by ZigFisher** [comment]
Thanks to All !
