### ISSUE TITLE
HI3516V300 + IMX291 Pinout?

### ISSUE THREAD

**Issue by Cybis320** [OpenIPC/firmware#1367]
Hi,
We have IMX291 cameras doing meteor research. I wanted to give openIPC a try. Does anyone know the location of UART port on that board?
Thank you!
Luc
![IMG_0099](https://github.com/OpenIPC/firmware/assets/133058544/696d788d-ece9-4109-8b81-80b9e6d4c2b3)

**Comment by widgetii** [comment]
![image](https://github.com/OpenIPC/firmware/assets/6576495/7ccb1569-fac5-4026-bef6-9085b3c7fa05)

**Comment by Cybis320** [comment]
Thank you! I've established communicating using the RPi GPIO, sweet!
