### ISSUE TITLE
Support for audio microphones (codecs, alsa, dual microphone, ...)

### ISSUE THREAD

**Issue by dumblob** [OpenIPC/firmware#145]
Hi, just discovered this interesting embedded linux.

I wonder if you support also microphones - especially regarding codecs, alsa (incl. userspace), dual microphone (I plan to us at least two)?

Thanks!

**Comment by widgetii** [comment]
Hi, OpenIPC is actually is specialized Linux distro which aim is to replace default factory firmware with hackable one. Everything supported by the vanilla Linux kernel is also supported by OpenIPC (with specific options selected on the build stage).
