### ISSUE TITLE
GK7205v200 with rtl8188ftv

### ISSUE THREAD

**Issue by Oldroid123** [OpenIPC/firmware#1460]
Hello. I installed the ultimate firmware. The problem is that my camera can only connect via the rtl8188ftv wifi module connected via USB. But I don't see it in the system at all. lsusb only detects hubs. I tried to compile the firmware with the rtl8188fu driver myself, but the situation did not change. When I try to measure the voltage at the module contacts, it is equal to 0. How can I get work wifi?
<details><summary>Booting log</summary>
<p>

U-Boot 2016.11-g852b5be (Jan 22 2024 - 21:07:52 +0300)gk7205v200

Relocation Offset is: 0372e000
Relocating to 43f2e000, new gd at 43eedef0, sp at 43eeded0
SPI Nor:  Check Flash Memory Controller v100 ... Found
SPI Nor ID Table Version 1.0
SPI Nor(cs 0) ID: 0xc2 0x20 0x19
Block:64KB Chip:32MB Name:"MX25L(256/257)XX"
SPI Nor total size: 32MB
NAND:  0 MiB
MMC:   sdhci: 0 (SD)
In:    serial
Out:   serial
Err:   serial
RAM size: 64MB
Net:   eth0
Warning: eth0 (eth0) using random MAC address - 96:1c:cb:5a:48:33

Press Ctrl-c to stop autoboot... 2
device 0 offset 0x50000, size 0x300000

SF: 3145728 bytes @ 0x50000 Read: OK
Booting kernel from Legacy Image at 42000000 ...
   Image Name:   Linux-4.9.37-gk7205v200
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    1858024 Bytes = 1.8 MiB
   Load Address: 40008000
   Entry Point:  40008000
   Loading Kernel Image ... OK

Starting kernel ...

Booting Linux on physical CPU 0x0
Linux version 4.9.37 (runner@fv-az1269-466) (buildroot-gcc-13.2.0) #1 Fri May 31 02:02:58 UTC 2024
CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c53c7d
CPU: div instructions available: patching division code
CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
OF: fdt:Machine model: Goke GK7205V200 DEMO Board
cma zone is not set!
Memory policy: Data cache writeback
CPU: All CPU(s) started in SVC mode.
Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 8128
Kernel command line: mem=32M console=ttyAMA0,115200 panic=20 root=/dev/mtdblock3 rootfstype=squashfs init=/init mtdparts=sfc:256k(boot),64k(env),3072k(kernel),10240k(rootfs),-(rootfs_data)
PID hash table entries: 128 (order: -3, 512 bytes)
Dentry cache hash table entries: 4096 (order: 2, 16384 bytes)
Inode-cache hash table entries: 2048 (order: 1, 8192 bytes)
Memory: 27056K/32768K available (3856K kernel code, 150K rwdata, 912K rodata, 192K init, 181K bss, 5712K reserved, 0K cma-reserved)
Virtual kernel memory layout:
    vector  : 0xffff0000 - 0xffff1000   (   4 kB)
    fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
    vmalloc : 0xc2800000 - 0xff800000   ( 976 MB)
    lowmem  : 0xc0000000 - 0xc2000000   (  32 MB)
    modules : 0xbf000000 - 0xc0000000   (  16 MB)
      .text : 0xc0008000 - 0xc03cc3a8   (3857 kB)
      .init : 0xc04b2000 - 0xc04e2000   ( 192 kB)
      .data : 0xc04e2000 - 0xc0507ae0   ( 151 kB)
       .bss : 0xc0509000 - 0xc0536468   ( 182 kB)
SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
NR_IRQS:16 nr_irqs:16 16
Gic dist init...
arm_arch_timer: Architected cp15 timer(s) running at 50.00MHz (phys).
clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0xb8812736b, max_idle_ns: 440795202655 ns
sched_clock: 56 bits at 50MHz, resolution 20ns, wraps every 4398046511100ns
Switching to timer-based delay loop, resolution 20ns
clocksource: arm,sp804: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 637086815595 ns
Console: colour dummy device 80x30
Calibrating delay loop (skipped), value calculated using timer frequency.. 100.00 BogoMIPS (lpj=500000)
pid_max: default: 32768 minimum: 301
Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
CPU: Testing write buffer coherency: ok
Setting up static identity map for 0x40008200 - 0x40008258
devtmpfs: initialized
VFP support v0.3: implementor 41 architecture 2 part 30 variant 7 rev 5
clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
futex hash table entries: 256 (order: -1, 3072 bytes)
pinctrl core: initialized pinctrl subsystem
NET: Registered protocol family 16
DMA: preallocated 256 KiB pool for atomic coherent allocations
Serial: AMBA PL011 UART driver
12040000.uart: ttyAMA0 at MMIO 0x12040000 (irq = 21, base_baud = 0) is a PL011 rev2
console [ttyAMA0] enabled
12041000.uart: ttyAMA1 at MMIO 0x12041000 (irq = 22, base_baud = 0) is a PL011 rev2
12042000.uart: ttyAMA2 at MMIO 0x12042000 (irq = 23, base_baud = 0) is a PL011 rev2
ssp-pl022 12070000.spi: ARM PL022 driver, device ID: 0x00041022
ssp-pl022 12070000.spi: mapped registers from 0x12070000 to c286f000
usbcore: registered new interface driver usbfs
usbcore: registered new interface driver hub
usbcore: registered new device driver usb
clocksource: Switched to clocksource arch_sys_counter
NET: Registered protocol family 2
TCP established hash table entries: 1024 (order: 0, 4096 bytes)
TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
TCP: Hash tables configured (established 1024 bind 1024)
UDP hash table entries: 256 (order: 0, 4096 bytes)
UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
NET: Registered protocol family 1
RPC: Registered named UNIX socket transport module.
RPC: Registered udp transport module.
RPC: Registered tcp transport module.
RPC: Registered tcp NFSv4.1 backchannel transport module.
workingset: timestamp_bits=30 max_order=13 bucket_order=0
squashfs: version 4.0 (2009/01/31) Phillip Lougher
jffs2: version 2.2 (NAND) (ZLIB) (RTIME) (c) 2001-2006 Red Hat, Inc.
Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
io scheduler noop registered
io scheduler deadline registered (default)
pl061_gpio 120b0000.gpio_chip: PL061 GPIO chip @0x120b0000 registered
pl061_gpio 120b1000.gpio_chip: PL061 GPIO chip @0x120b1000 registered
pl061_gpio 120b2000.gpio_chip: PL061 GPIO chip @0x120b2000 registered
pl061_gpio 120b4000.gpio_chip: PL061 GPIO chip @0x120b4000 registered
pl061_gpio 120b5000.gpio_chip: PL061 GPIO chip @0x120b5000 registered
pl061_gpio 120b6000.gpio_chip: PL061 GPIO chip @0x120b6000 registered
pl061_gpio 120b7000.gpio_chip: PL061 GPIO chip @0x120b7000 registered
pl061_gpio 120b8000.gpio_chip: PL061 GPIO chip @0x120b8000 registered
brd: module loaded
loop: module loaded
bsp-sfc bsp_spi_nor.0: SPI Nor ID Table Version 1.2
bsp-sfc bsp_spi_nor.0: Force global unlock
bsp-sfc bsp_spi_nor.0: SR1:[02]->[00]
bsp-sfc bsp_spi_nor.0: all blocks are unlocked.
bsp-sfc bsp_spi_nor.0: SR1 [00], SR2 [00], SR3 [00]
bsp-sfc bsp_spi_nor.0: mx25l25635f (Chipsize 32 Mbytes, Blocksize 64KiB)
5 cmdlinepart partitions found on MTD device sfc
5 cmdlinepart partitions found on MTD device sfc
Creating 5 MTD partitions on "sfc":
0x000000000000-0x000000040000 : "boot"
0x000000040000-0x000000050000 : "env"
0x000000050000-0x000000350000 : "kernel"
0x000000350000-0x000000d50000 : "rootfs"
0x000000d50000-0x000002000000 : "rootfs_data"
SPI Nand ID Table Version 2.7
Cannot found a valid SPI Nand Device
bsp_spi_nand_probe(157): Error: driver probe, result: -19
FEPHY:addr=1, la_am=0xa, ldo_am=0x5, r_tuning=0x24
libphy: femac_mii_bus: probed
libphy: Fixed MDIO Bus: probed
femac 10040000.ethernet: using random MAC address ee:51:15:37:f8:f0
Generic PHY 10041100.mdio:01: attached PHY driver [Generic PHY] (mii_bus:phy_addr=10041100.mdio:01, irq=-1)
phy_id=0x20669906, phy_mode=mii
xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 1
xhci-hcd xhci-hcd.0.auto: hcc params 0x0220fe6c hci version 0x110 quirks 0x20010010
xhci-hcd xhci-hcd.0.auto: irq 116, io mem 0x10030000
hub 1-0:1.0: USB hub found
hub 1-0:1.0: 1 port detected
xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 2
usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
hub 2-0:1.0: USB hub found
hub 2-0:1.0: hub can't support USB3.0
goke_rtc 120e0000.rtc: rtc core: registered 120e0000.rtc as rtc0
goke_rtc 120e0000.rtc: RTC driver for goke enabled
i2c /dev entries driver
goke-i2c 12060000.i2c: goke-i2c0@100000hz registered
goke-i2c 12061000.i2c: goke-i2c1@100000hz registered
goke-i2c 12062000.i2c: goke-i2c2@100000hz registered
sdhci: Secure Digital Host Controller Interface driver
sdhci: Copyright(c) Pierre Ossman
sdhci-pltfm: SDHCI platform and OF driver helper
mmc0: SDHCI controller on 10010000.sdhci [10010000.sdhci] using ADMA in legacy mode
mmc1: SDHCI controller on 10020000.sdhci [10020000.sdhci] using ADMA in legacy mode
ip_tables: (C) 2000-2006 Netfilter Core Team
NET: Registered protocol family 10
NET: Registered protocol family 17
bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
mmc0: new high speed SDXC card at address aaaa
mmcblk0: mmc0:aaaa SC128 119 GiB
 mmcblk0: p1
goke_rtc 120e0000.rtc: hctosys: unable to read the hardware clock
VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
devtmpfs: mounted
Freeing unused kernel memory: 192K (c04b2000 - c04e2000)
This architecture does not have kernel memory protection.
Fri May 31 02:06:37 GMT 2024
random: seedrng: uninitialized urandom read (256 bytes read)
Saving 2048 bits of non-creditable seed for next boot
Starting syslogd: OK
Starting klogd: OK
Running sysctl: OK
Starting rngd: OK
Starting iptables: OK
Loading modules...
modprobe: module exfat not found in modules.dep
Starting mdev...
Starting network...
udhcpc: started, v1.36.1
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: no lease, forking to background
Starting ntpd: OK
Starting dropbear: OK
Starting crond: OK
Loading vendor modules...
mmz_start: 0x42000000, mmz_size: 32M
Allocator selected as gk...
mem=32M console=ttyAMA0,115200 panic=20 rootfstype=squashfs root=/dev/mtdblock3 init=/init mtdparts=${mtdparts} mmz_allocator=gk
ioctl SPI_IOC_WR_MODE err, value = 11 ret = -1
rmmod: can't unload module 'gk7205v200_isp': No such file or directory
rmmod: can't unload module 'gk7205v200_base': Resource temporarily unavailable
goke: Get data from ipcinfo and set SENSOR as unknown
goke: Writing unknown to U-Boot ENV
goke: SENSOR is not detected, aborting...
Starting majestic: OK

</p>
</details> 

lsusb:
```
Bus 001 Device 001: ID 1d6b:0002
Bus 002 Device 001: ID 1d6b:0003

``` 

<details><summary>Dmesg</summary>
<p>

Booting Linux on physical CPU 0x0
Linux version 4.9.37 (runner@fv-az1269-466) (buildroot-gcc-13.2.0) #1 Fri May 31 02:02:58 UTC 2024
CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c53c7d
CPU: div instructions available: patching division code
CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
OF: fdt:Machine model: Goke GK7205V200 DEMO Board
cma zone is not set!
Memory policy: Data cache writeback
On node 0 totalpages: 8192
free_area_init_node: node 0, pgdat c05072d8, node_mem_map c1fbb000
  Normal zone: 64 pages used for memmap
  Normal zone: 0 pages reserved
  Normal zone: 8192 pages, LIFO batch:0
CPU: All CPU(s) started in SVC mode.
pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
pcpu-alloc: [0] 0
Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 8128
Kernel command line: mem=32M console=ttyAMA0,115200 panic=20 root=/dev/mtdblock3 rootfstype=squashfs init=/init mtdparts=sfc:256k(boot),64k(env),3072k(kernel),10240k(rootfs),-(rootfs_data)
PID hash table entries: 128 (order: -3, 512 bytes)
Dentry cache hash table entries: 4096 (order: 2, 16384 bytes)
Inode-cache hash table entries: 2048 (order: 1, 8192 bytes)
Memory: 27056K/32768K available (3856K kernel code, 150K rwdata, 912K rodata, 192K init, 181K bss, 5712K reserved, 0K cma-reserved)
Virtual kernel memory layout:
    vector  : 0xffff0000 - 0xffff1000   (   4 kB)
    fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
    vmalloc : 0xc2800000 - 0xff800000   ( 976 MB)
    lowmem  : 0xc0000000 - 0xc2000000   (  32 MB)
    modules : 0xbf000000 - 0xc0000000   (  16 MB)
      .text : 0xc0008000 - 0xc03cc3a8   (3857 kB)
      .init : 0xc04b2000 - 0xc04e2000   ( 192 kB)
      .data : 0xc04e2000 - 0xc0507ae0   ( 151 kB)
       .bss : 0xc0509000 - 0xc0536468   ( 182 kB)
SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
NR_IRQS:16 nr_irqs:16 16
Gic dist init...
arm_arch_timer: Architected cp15 timer(s) running at 50.00MHz (phys).
clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0xb8812736b, max_idle_ns: 440795202655 ns
sched_clock: 56 bits at 50MHz, resolution 20ns, wraps every 4398046511100ns
Switching to timer-based delay loop, resolution 20ns
clocksource: arm,sp804: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 637086815595 ns
Console: colour dummy device 80x30
Calibrating delay loop (skipped), value calculated using timer frequency.. 100.00 BogoMIPS (lpj=500000)
pid_max: default: 32768 minimum: 301
Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
CPU: Testing write buffer coherency: ok
Setting up static identity map for 0x40008200 - 0x40008258
devtmpfs: initialized
VFP support v0.3: implementor 41 architecture 2 part 30 variant 7 rev 5
clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
futex hash table entries: 256 (order: -1, 3072 bytes)
pinctrl core: initialized pinctrl subsystem
NET: Registered protocol family 16
DMA: preallocated 256 KiB pool for atomic coherent allocations
Serial: AMBA PL011 UART driver
12040000.uart: ttyAMA0 at MMIO 0x12040000 (irq = 21, base_baud = 0) is a PL011 rev2
console [ttyAMA0] enabled
12041000.uart: ttyAMA1 at MMIO 0x12041000 (irq = 22, base_baud = 0) is a PL011 rev2
12042000.uart: ttyAMA2 at MMIO 0x12042000 (irq = 23, base_baud = 0) is a PL011 rev2
ssp-pl022 12070000.spi: ARM PL022 driver, device ID: 0x00041022
ssp-pl022 12070000.spi: mapped registers from 0x12070000 to c286f000
usbcore: registered new interface driver usbfs
usbcore: registered new interface driver hub
usbcore: registered new device driver usb
clocksource: Switched to clocksource arch_sys_counter
NET: Registered protocol family 2
TCP established hash table entries: 1024 (order: 0, 4096 bytes)
TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
TCP: Hash tables configured (established 1024 bind 1024)
UDP hash table entries: 256 (order: 0, 4096 bytes)
UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
NET: Registered protocol family 1
RPC: Registered named UNIX socket transport module.
RPC: Registered udp transport module.
RPC: Registered tcp transport module.
RPC: Registered tcp NFSv4.1 backchannel transport module.
workingset: timestamp_bits=30 max_order=13 bucket_order=0
squashfs: version 4.0 (2009/01/31) Phillip Lougher
jffs2: version 2.2 (NAND) (ZLIB) (RTIME) (c) 2001-2006 Red Hat, Inc.
yaffs: yaffs Installing.
Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
io scheduler noop registered
io scheduler deadline registered (default)
pl061_gpio 120b0000.gpio_chip: PL061 GPIO chip @0x120b0000 registered
pl061_gpio 120b1000.gpio_chip: PL061 GPIO chip @0x120b1000 registered
pl061_gpio 120b2000.gpio_chip: PL061 GPIO chip @0x120b2000 registered
pl061_gpio 120b4000.gpio_chip: PL061 GPIO chip @0x120b4000 registered
pl061_gpio 120b5000.gpio_chip: PL061 GPIO chip @0x120b5000 registered
pl061_gpio 120b6000.gpio_chip: PL061 GPIO chip @0x120b6000 registered
pl061_gpio 120b7000.gpio_chip: PL061 GPIO chip @0x120b7000 registered
pl061_gpio 120b8000.gpio_chip: PL061 GPIO chip @0x120b8000 registered
brd: module loaded
loop: module loaded
bsp-sfc bsp_spi_nor.0: SPI Nor ID Table Version 1.2
bsp-sfc bsp_spi_nor.0: Force global unlock
bsp-sfc bsp_spi_nor.0: SR1:[02]->[00]
bsp-sfc bsp_spi_nor.0: all blocks are unlocked.
bsp-sfc bsp_spi_nor.0: SR1 [00], SR2 [00], SR3 [00]
bsp-sfc bsp_spi_nor.0: mx25l25635f (Chipsize 32 Mbytes, Blocksize 64KiB)
5 cmdlinepart partitions found on MTD device sfc
5 cmdlinepart partitions found on MTD device sfc
Creating 5 MTD partitions on "sfc":
0x000000000000-0x000000040000 : "boot"
0x000000040000-0x000000050000 : "env"
0x000000050000-0x000000350000 : "kernel"
0x000000350000-0x000000d50000 : "rootfs"
0x000000d50000-0x000002000000 : "rootfs_data"
SPI Nand ID Table Version 2.7
Cannot found a valid SPI Nand Device
bsp_spi_nand_probe(157): Error: driver probe, result: -19
FEPHY:addr=1, la_am=0xa, ldo_am=0x5, r_tuning=0x24
libphy: femac_mii_bus: probed
libphy: Fixed MDIO Bus: probed
femac 10040000.ethernet: using random MAC address ee:51:15:37:f8:f0
Generic PHY 10041100.mdio:01: attached PHY driver [Generic PHY] (mii_bus:phy_addr=10041100.mdio:01, irq=-1)
phy_id=0x20669906, phy_mode=mii
xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 1
xhci-hcd xhci-hcd.0.auto: hcc params 0x0220fe6c hci version 0x110 quirks 0x20010010
xhci-hcd xhci-hcd.0.auto: irq 116, io mem 0x10030000
hub 1-0:1.0: USB hub found
hub 1-0:1.0: 1 port detected
xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 2
usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
hub 2-0:1.0: USB hub found
hub 2-0:1.0: hub can't support USB3.0
goke_rtc 120e0000.rtc: rtc core: registered 120e0000.rtc as rtc0
goke_rtc 120e0000.rtc: RTC driver for goke enabled
i2c /dev entries driver
goke-i2c 12060000.i2c: goke-i2c0@100000hz registered
goke-i2c 12061000.i2c: goke-i2c1@100000hz registered
goke-i2c 12062000.i2c: goke-i2c2@100000hz registered
sdhci: Secure Digital Host Controller Interface driver
sdhci: Copyright(c) Pierre Ossman
sdhci-pltfm: SDHCI platform and OF driver helper
mmc0: SDHCI controller on 10010000.sdhci [10010000.sdhci] using ADMA in legacy mode
mmc1: SDHCI controller on 10020000.sdhci [10020000.sdhci] using ADMA in legacy mode
ip_tables: (C) 2000-2006 Netfilter Core Team
NET: Registered protocol family 10
NET: Registered protocol family 17
bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
mmc0: new high speed SDXC card at address aaaa
mmcblk0: mmc0:aaaa SC128 119 GiB
 mmcblk0: p1
goke_rtc 120e0000.rtc: hctosys: unable to read the hardware clock
VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
devtmpfs: mounted
Freeing unused kernel memory: 192K (c04b2000 - c04e2000)
This architecture does not have kernel memory protection.
random: seedrng: uninitialized urandom read (256 bytes read)
random: rngd: uninitialized urandom read (4 bytes read)
random: rngd: uninitialized urandom read (4 bytes read)
random: rngd: uninitialized urandom read (2500 bytes read)
random: crng init done
yaffs: dev is 187695105 name is "mmcblk0p1" rw
yaffs: passed flags ""
yaffs: yaffs: Attempting MTD mount of 179.1,"mmcblk0p1"
yaffs: MTD device does not support have the right page sizes
yaffs: dev is 187695105 name is "mmcblk0p1" rw
yaffs: passed flags ""
yaffs: yaffs: Attempting MTD mount of 179.1,"mmcblk0p1"
yaffs: NAND geometry problems: chunk size 1, type is yaffs2, inband_tags 1
FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
open_sys_config: loading out-of-tree module taints kernel.
FUNC:parse_sensor_clock line:125  SNS: is [unknown]!
FUNC:parse_sensor_bus_type line:88  SNS is [unknown]  !
==== online_flag=0, cmos_yuv_flag=0, sensor=unknown, chip=gk7205v200, board=demo====
==== g_quick_start_flag=0 ====
sysconfig init success!
Module media: init ok
Media Memory Zone Manager
osal 1.0 init success!
gk7205v200_base: module license 'Proprietary' taints kernel.
Disabling lock debugging due to kernel taint
ISP Mod init!
Load sensor_spi.ko OK !
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
Unload sensor_spi.ko OK!
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
goke-i2c 12060000.i2c: wait idle timeout, RIS: 0x10, SR: 0xa0000
root@openipc-gk7205v200:/lib/modules/4.9.37#

</p>
</details>

**Comment by cronyx** [comment]
Your board has USB power management, you need to find the GPIO responsible for supplying power. Perhaps a [table with known GPIOs](https://github.com/OpenIPC/wiki/blob/master/en/gpio-settings.md) for your soc model will help you. In any case, you can always find it using the bruteforce method.

**Comment by Oldroid123** [comment]
> Your board has USB power management, you need to find the GPIO responsible for supplying power. Perhaps a [table with known GPIOs](https://github.com/OpenIPC/wiki/blob/master/en/gpio-settings.md) for your soc model will help you. In any case, you can always find it using the bruteforce method.

I have enabled all 23 GPIO ON, but it is 0 voltage on wifi module

**Comment by Oldroid123** [comment]
Okey, i can power on and power off my wifi with 57 gpio. But if i try to build firmware with driver, i have error. Where i can get driver for my device?

**Comment by danieltwagner** [comment]
I found this thread when googling and thought I'd also post that for my gk7205v200 with built-in wifi pulling GPIO 9 low (`echo "0" > /sys/class/gpio/gpio9/value`) worked, much as indicated in [the table with known GPIOs](https://github.com/OpenIPC/wiki/blob/master/en/gpio-settings.md) that @cronyx linked above. Thanks for the helpful pointer.

The resulting deviceid `0bda:f72b` finally pointed me at the fact that there is already an [existing configuration](https://github.com/OpenIPC/firmware/blob/6d2dd985806c47ab60b86e73dee605a5f59464e2/general/overlay/etc/wireless/usb#L52) for my particular board and that [creating a new build with the wifi driver](https://github.com/OpenIPC/wiki/blob/master/en/adding-wifi-driver.md) and then [enabling it](https://github.com/OpenIPC/wiki/blob/master/en/wireless-settings.md) using `fw_setenv` was pretty straight-forward once I knew where to look. Maybe this will help someone else arriving via search results.
