### ISSUE TITLE
Не работает сеть на HI3516CV300

### ISSUE THREAD

**Issue by doctor-dark** [OpenIPC/firmware#161]
Во время загрузки в логах вижу ошибку:
`[    0.943271] hisi-femac 10050000.ethernet: connect to PHY failed!`

Соответственно сети нет. Загрузиться по nfs не могу
Полный лог загрузки OpenIPC
`hi3516cv300 System startup

U-Boot 2010.06 (Aug 20 2020 - 10:49:38)

Check Flash Memory Controller v100 ... Found
SPI Nand(cs 0) ID: 0x98 0xc2 Name:"TC58CVG0S3H"
Block:128KB Page:2KB Chip:128MB*1 OOB:64B ECC:8bit/512
ECC provided by Flash Memory Controller
SPI Nand total size: 128MB
MMC:
EMMC/MMC/SD controller initialization.
Card did not respond to voltage select!
No EMMC/MMC/SD device found !

EMMC/MMC/SD controller initialization.
Card did not respond to voltage select!
No EMMC/MMC/SD device found !
In:    serial
Out:   serial
Err:   serial
*No SD card found!
USB:   scanning bus for devices... 1 USB Device(s) found
0 Storage Device(s) found
Hit any key to stop autoboot:  0
hi3516cv300-vc #
hi3516cv300-vc # tftp 0x82000000 openwrt
Hisilicon ETH net controler
phyaddr=[3]
MAC:   00-00-23-34-45-66
eth0 : phy status change : LINK=DOWN : DUPLEX=FULL : SPEED=100M
eth0 : phy status change : LINK=UP : DUPLEX=FULL : SPEED=100M
TFTP from server 192.168.1.2; our IP address is 192.168.1.10
Download Filename 'openwrt'.
Download to address: 0x82000000
Downloading: #################################################
done
Bytes transferred = 1901843 (1d0513 hex)
hi3516cv300-vc # bootm 0x82000000
## Booting kernel from Legacy Image at 82000000 ...
   Image Name:   OpenIPC.org | Linux-3.18.20
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    1901779 Bytes = 1.8 MiB
   Load Address: 80008000
   Entry Point:  80008000
   Loading Kernel Image ... OK
OK

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Linux version 3.18.20 (runner@fv-az32-73) (gcc version 4.8.3 (OpenWrt/Linaro GCC 4.8-2014.04 latest-178-g157e03c47e) ) #1 Sat Jul 10 19:45:12 UTC 2021
[    0.000000] CPU: ARM926EJ-S [41069265] revision 5 (ARMv5TEJ), cr=0005317f
[    0.000000] CPU: VIVT data cache, VIVT instruction cache
[    0.000000] Machine model: Hisilicon Hi3516CV300 DEMO Board
[    0.000000] Memory policy: Data cache writeback
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 130048
[    0.000000] Kernel command line: =mem=64M console=ttyAMA0,115200 root=/dev/nfs nfsroot=192.168.1.2:/srv/nfs/openipc_rootfs ip=dhcp
[    0.000000] PID hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 514440K/524288K available (3595K kernel code, 169K rwdata, 1028K rodata, 156K init, 246K bss, 9848K reserved, 0K highmem)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xffc00000 - 0xffe00000   (2048 kB)
[    0.000000]     vmalloc : 0xe0800000 - 0xff000000   ( 488 MB)
[    0.000000]     lowmem  : 0xc0000000 - 0xe0000000   ( 512 MB)
[    0.000000]     pkmap   : 0xbfe00000 - 0xc0000000   (   2 MB)
[    0.000000]     modules : 0xbf000000 - 0xbfe00000   (  14 MB)
[    0.000000]       .text : 0xc0008000 - 0xc048c3c4   (4625 kB)
[    0.000000]       .init : 0xc048d000 - 0xc04b4000   ( 156 kB)
[    0.000000]       .data : 0xc04b4000 - 0xc04de7c0   ( 170 kB)
[    0.000000]        .bss : 0xc04de7c0 - 0xc051c050   ( 247 kB)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS:16 nr_irqs:16 16
[    0.000000] VIC @e0800000: id 0x00641190, vendor 0x41
[    0.000030] sched_clock: 32 bits at 3000kHz, resolution 333ns, wraps every 1431655765682ns
[    0.000701] Console: colour dummy device 80x30
[    0.000753] Calibrating delay loop... 398.13 BogoMIPS (lpj=1990656)
[    0.050051] pid_max: default: 32768 minimum: 301
[    0.050217] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.050237] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.051311] Initializing cgroup subsys devices
[    0.051351] Initializing cgroup subsys freezer
[    0.051374] Initializing cgroup subsys blkio
[    0.051426] CPU: Testing write buffer coherency: ok
[    0.052043] Setting up static identity map for 0x8036c448 - 0x8036c4a0
[    0.053871] devtmpfs: initialized
[    0.055315] VFP support v0.3: not present
[    0.056020] pinctrl core: initialized pinctrl subsystem
[    0.063706] NET: Registered protocol family 16
[    0.064978] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.078723] Serial: AMBA PL011 UART driver
[    0.079034] 12100000.uart: ttyAMA0 at MMIO 0x12100000 (irq = 21, base_baud = 0) is a PL011 rev2
[    0.351336] console [ttyAMA0] enabled
[    0.364661] SCSI subsystem initialized
[    0.368566] ssp-pl022 12120000.spi: ARM PL022 driver, device ID: 0x00800022
[    0.375688] ssp-pl022 12120000.spi: mapped registers from 0x12120000 to e086c000
[    0.385080] usbcore: registered new interface driver usbfs
[    0.390793] usbcore: registered new interface driver hub
[    0.396223] usbcore: registered new device driver usb
[    0.403207] Switched to clocksource arm,sp804
[    0.423473] NET: Registered protocol family 2
[    0.429345] TCP established hash table entries: 4096 (order: 2, 16384 bytes)
[    0.436660] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
[    0.443314] TCP: Hash tables configured (established 4096 bind 4096)
[    0.449818] TCP: reno registered
[    0.453055] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.458976] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.465639] NET: Registered protocol family 1
[    0.470552] RPC: Registered named UNIX socket transport module.
[    0.476548] RPC: Registered udp transport module.
[    0.481251] RPC: Registered tcp transport module.
[    0.485986] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.494950] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.519222] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.527001] jffs2: version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
[    0.534656] msgmni has been set to 1004
[    0.540122] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 254)
[    0.547647] io scheduler noop registered
[    0.551582] io scheduler deadline registered (default)
[    0.557148] io scheduler cfq registered
[    0.567618] pinctrl-single 12040000.pinmux: 66 pins at pa e08ca000 size 264
[    0.575221] pinctrl-single 12040800.pinconf: 76 pins at pa e08cc800 size 304
[    0.583068] pl061_gpio 12140000.gpio: PL061 GPIO chip @0x12140000 registered
[    0.590715] pl061_gpio 12141000.gpio: PL061 GPIO chip @0x12141000 registered
[    0.598372] pl061_gpio 12142000.gpio: PL061 GPIO chip @0x12142000 registered
[    0.606054] pl061_gpio 12143000.gpio: PL061 GPIO chip @0x12143000 registered
[    0.613709] pl061_gpio 12144000.gpio: PL061 GPIO chip @0x12144000 registered
[    0.621300] pl061_gpio 12145000.gpio: PL061 GPIO chip @0x12145000 registered
[    0.629022] pl061_gpio 12146000.gpio: PL061 GPIO chip @0x12146000 registered
[    0.636685] pl061_gpio 12147000.gpio: PL061 GPIO chip @0x12147000 registered
[    0.644353] pl061_gpio 12148000.gpio: PL061 GPIO chip @0x12148000 registered
[    0.664639] brd: module loaded
[    0.670259] hisi-sfc hisi_spi_nor.0: unrecognized JEDEC id bytes: ff, 98, c2
[    0.677402] hisi-sfc hisi_spi_nor.0: spi nor register fail!
[    0.683061] hisi-sfc: probe of hisi_spi_nor.0 failed with error -2
[    0.689913] SPI Nand ID Table Version 2.4
[    0.695070] SPI Nand(cs 0) ID: 0x98 0xc2
[    0.699021] nand: device found, Manufacturer ID: 0x98, Chip ID: 0xc2
[    0.705411] nand: Toshiba TC58CVG0S3H
[    0.709073] nand: 128MiB, SLC, page size: 2048
[    0.713532] Nand(Auto): OOB:128B ECC:24bit/1k
[    0.717827] nand:  ECC provided by Flash Memory Controller
[    0.726122] libphy: hisi_femac_mii_bus: probed
[    0.943271] hisi-femac 10050000.ethernet: connect to PHY failed!
[    0.949658] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.956290] ehci-platform: EHCI generic platform driver
[    0.961817] ehci-platform 10120000.ehci: EHCI Host Controller
[    0.967715] ehci-platform 10120000.ehci: new USB bus registered, assigned bus number 1
[    0.976025] ehci-platform 10120000.ehci: irq 31, io mem 0x10120000
[    0.993298] ehci-platform 10120000.ehci: USB 2.0 started, EHCI 1.00
[    1.000972] hub 1-0:1.0: USB hub found
[    1.004873] hub 1-0:1.0: 1 port detected
[    1.009516] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    1.015811] ohci-platform: OHCI generic platform driver
[    1.021317] ohci-platform 10110000.ohci: Generic Platform OHCI controller
[    1.028256] ohci-platform 10110000.ohci: new USB bus registered, assigned bus number 2
[    1.036438] ohci-platform 10110000.ohci: irq 32, io mem 0x10110000
[    1.098697] hub 2-0:1.0: USB hub found
[    1.102527] hub 2-0:1.0: 1 port detected
[    1.107269] i2c /dev entries driver
[    1.111644] hibvt-i2c 12110000.i2c: hibvt-i2c0@100000hz registered
[    1.118745] hibvt-i2c 12112000.i2c: hibvt-i2c1@100000hz registered
[    1.125987] himci: mmc host probe
[    1.293345] himci: mmc host probe
[    1.463345] himci: mmc host probe
[    1.633804] hidraw: raw HID events driver (C) Jiri Kosina
[    1.640587] usbcore: registered new interface driver usbhid
[    1.646226] usbhid: USB HID core driver
[    1.651076] TCP: cubic registered
[    1.654495] NET: Registered protocol family 17
[  108.833977] VFS: Unable to mount root fs via NFS, trying floppy.
[  108.840602] VFS: Cannot open root device "nfs" or unknown-block(2,0): error -6
[  108.847893] Please append a correct "root=" boot option; here are the available partitions:
[  108.856296] 1f00          131072 mtdblock0  (driver?)
[  108.861356] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(2,0)
[  108.869622] CPU: 0 PID: 1 Comm: swapper Not tainted 3.18.20 #1
[  108.875501] [<c00133e4>] (unwind_backtrace) from [<c0011664>] (show_stack+0x10/0x14)
[  108.883262] [<c0011664>] (show_stack) from [<c03670dc>] (panic+0x84/0x1e4)
[  108.890152] [<c03670dc>] (panic) from [<c048e10c>] (mount_block_root+0x184/0x228)
[  108.897640] [<c048e10c>] (mount_block_root) from [<c048e390>] (mount_root+0xe4/0x10c)
[  108.905474] [<c048e390>] (mount_root) from [<c048e518>] (prepare_namespace+0x160/0x1c0)
[  108.913481] [<c048e518>] (prepare_namespace) from [<c048ddac>] (kernel_init_freeable+0x170/0x1b4)
[  108.922355] [<c048ddac>] (kernel_init_freeable) from [<c0366a38>] (kernel_init+0x8/0xec)
[  108.930450] [<c0366a38>] (kernel_init) from [<c000e468>] (ret_from_fork+0x14/0x2c)
[  108.938019] ---[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(2,0)
`

Лог оригинальной прошивки
`hi3516cv300 System startup

U-Boot 2010.06 (Aug 20 2020 - 10:49:38)

Check Flash Memory Controller v100 ... Found
SPI Nand(cs 0) ID: 0x98 0xc2 Name:"TC58CVG0S3H"
Block:128KB Page:2KB Chip:128MB*1 OOB:64B ECC:8bit/512 
ECC provided by Flash Memory Controller
SPI Nand total size: 128MB
MMC:   
EMMC/MMC/SD controller initialization.
Card did not respond to voltage select!
No EMMC/MMC/SD device found !

EMMC/MMC/SD controller initialization.
Card did not respond to voltage select!
No EMMC/MMC/SD device found !
*** Warning - bad CRC or NAND, using default environment

In:    serial
Out:   serial
Err:   serial
*No SD card found!
USB:   scanning bus for devices... 1 USB Device(s) found
0 Storage Device(s) found
Hit any key to stop autoboot:  1  0 
Set gpio: 40->1
Set gpio: 7->0
Set gpio: 72->0
Set gpio: 73->0
No mmc found

NAND read: device 0 offset 0x200000, size 0x500000
 5242880 bytes read: OK
## Booting kernel from Legacy Image at 82000000 ...
   Image Name:   Linux-3.18.20
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    4692171 Bytes = 4.5 MiB
   Load Address: 80008000
   Entry Point:  80008000
   Loading Kernel Image ... OK
OK

Starting kernel ...

Booting Linux on physical CPU 0x0
Initializing cgroup subsys cpu
Linux version 3.18.20 (root@runner-5xrkcpsv-project-22-concurrent-0) (gcc version 4.9.4 20150629 (prerelease) (Hisilicon_v500_20170615) ) #1 Thu Aug 5 13:02:30 UTC 2021
CPU: ARM926EJ-S [41069265] revision 5 (ARMv5TEJ), cr=0005317f
CPU: VIVT data cache, VIVT instruction cache
Machine model: Hisilicon Hi3516CV300 DEMO Board
Memory policy: Data cache writeback
Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 16256
Kernel command line: mem=64M console=ttyAMA0,115200 rootfstype=ramfs mtdparts=hinand:1024K(boot),1024K(tech),5120K(kernel),16384K(app),-(config) hw_type=1205 ubi.mtd=3,2048
PID hash table entries: 256 (order: -2, 1024 bytes)
Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
Memory: 57316K/65536K available (4124K kernel code, 190K rwdata, 1100K rodata, 1836K init, 256K bss, 8220K reserved, 0K highmem)
Virtual kernel memory layout:
    vector  : 0xffff0000 - 0xffff1000   (   4 kB)
    fixmap  : 0xffc00000 - 0xffe00000   (2048 kB)
    vmalloc : 0xc4800000 - 0xff000000   ( 936 MB)
    lowmem  : 0xc0000000 - 0xc4000000   (  64 MB)
    pkmap   : 0xbfe00000 - 0xc0000000   (   2 MB)
    modules : 0xbf000000 - 0xbfe00000   (  14 MB)
      .text : 0xc0008000 - 0xc0522738   (5226 kB)
      .init : 0xc0523000 - 0xc06ee000   (1836 kB)
      .data : 0xc06ee000 - 0xc071d980   ( 191 kB)
       .bss : 0xc071d980 - 0xc075dbb8   ( 257 kB)
SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
NR_IRQS:16 nr_irqs:16 16
VIC @c4800000: id 0x00641190, vendor 0x41
sched_clock: 32 bits at 3000kHz, resolution 333ns, wraps every 1431655765682ns
Console: colour dummy device 80x30
Calibrating delay loop... 398.13 BogoMIPS (lpj=1990656)
pid_max: default: 32768 minimum: 301
Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
CPU: Testing write buffer coherency: ok
Setting up static identity map for 0x803f10b0 - 0x803f1108
devtmpfs: initialized
VFP support v0.3: not present
pinctrl core: initialized pinctrl subsystem
NET: Registered protocol family 16
DMA: preallocated 256 KiB pool for atomic coherent allocations
Serial: AMBA PL011 UART driver
12100000.uart: ttyAMA0 at MMIO 0x12100000 (irq = 21, base_baud = 0) is a PL011 rev2
console [ttyAMA0] enabled
SCSI subsystem initialized
ssp-pl022 12120000.spi: ARM PL022 driver, device ID: 0x00800022
ssp-pl022 12120000.spi: mapped registers from 0x12120000 to c486c000
usbcore: registered new interface driver usbfs
usbcore: registered new interface driver hub
usbcore: registered new device driver usb
Switched to clocksource arm,sp804
NET: Registered protocol family 2
TCP established hash table entries: 1024 (order: 0, 4096 bytes)
TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
TCP: Hash tables configured (established 1024 bind 1024)
TCP: reno registered
UDP hash table entries: 256 (order: 0, 4096 bytes)
UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
NET: Registered protocol family 1
RPC: Registered named UNIX socket transport module.
RPC: Registered udp transport module.
RPC: Registered tcp transport module.
RPC: Registered tcp NFSv4.1 backchannel transport module.
futex hash table entries: 256 (order: -1, 3072 bytes)
squashfs: version 4.0 (2009/01/31) Phillip Lougher
jffs2: version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
msgmni has been set to 111
Block layer SCSI generic (bsg) driver version 0.4 loaded (major 254)
io scheduler noop registered
io scheduler deadline registered (default)
io scheduler cfq registered
pinctrl-single 12040000.pinmux: 66 pins at pa c48c8000 size 264
pinctrl-single 12040800.pinconf: 76 pins at pa c48ca800 size 304
pl061_gpio 12140000.gpio: PL061 GPIO chip @0x12140000 registered
pl061_gpio 12141000.gpio: PL061 GPIO chip @0x12141000 registered
pl061_gpio 12142000.gpio: PL061 GPIO chip @0x12142000 registered
pl061_gpio 12143000.gpio: PL061 GPIO chip @0x12143000 registered
pl061_gpio 12144000.gpio: PL061 GPIO chip @0x12144000 registered
pl061_gpio 12145000.gpio: PL061 GPIO chip @0x12145000 registered
pl061_gpio 12146000.gpio: PL061 GPIO chip @0x12146000 registered
pl061_gpio 12147000.gpio: PL061 GPIO chip @0x12147000 registered
pl061_gpio 12148000.gpio: PL061 GPIO chip @0x12148000 registered
brd: module loaded
hisi-sfc hisi_spi_nor.0: unrecognized JEDEC id bytes: ff, 98, c2
hisi-sfc hisi_spi_nor.0: spi nor register fail!
hisi-sfc: probe of hisi_spi_nor.0 failed with error -2
SPI Nand ID Table Version 2.2
SPI Nand(cs 0) ID: 0x98 0xc2
nand: device found, Manufacturer ID: 0x98, Chip ID: 0xc2
nand: Toshiba TC58CVG0S3H
nand: 128MiB, SLC, page size: 2048
Nand(Auto): OOB:64B ECC:8bit/512 
nand:  ECC provided by Flash Memory Controller
5 cmdlinepart partitions found on MTD device hinand
5 cmdlinepart partitions found on MTD device hinand
Creating 5 MTD partitions on "hinand":
0x000000000000-0x000000100000 : "boot"
0x000000100000-0x000000200000 : "tech"
0x000000200000-0x000000700000 : "kernel"
0x000000700000-0x000001700000 : "app"
0x000001700000-0x000008000000 : "config"
libphy: hisi_femac_mii_bus: probed
config RTL8201 phy led.
hisi-femac 10050000.ethernet: phy_id=0x001cc816, phy_addr=3, phy_mode=rmii
hisi-femac 10050000.ethernet: using random MAC address d2:c1:bd:93:33:28
ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
ehci-platform: EHCI generic platform driver
ehci-platform 10120000.ehci: EHCI Host Controller
ehci-platform 10120000.ehci: new USB bus registered, assigned bus number 1
ehci-platform 10120000.ehci: irq 31, io mem 0x10120000
ehci-platform 10120000.ehci: USB 2.0 started, EHCI 1.00
hub 1-0:1.0: USB hub found
hub 1-0:1.0: 1 port detected
ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
ohci-platform: OHCI generic platform driver
ohci-platform 10110000.ohci: Generic Platform OHCI controller
ohci-platform 10110000.ohci: new USB bus registered, assigned bus number 2
ohci-platform 10110000.ohci: irq 32, io mem 0x10110000
hub 2-0:1.0: USB hub found
hub 2-0:1.0: 1 port detected
usbcore: registered new interface driver usb-storage
mousedev: PS/2 mouse device common for all mice
i2c /dev entries driver
hibvt-i2c 12110000.i2c: hibvt-i2c0@100000hz registered
hibvt-i2c 12112000.i2c: hibvt-i2c1@100000hz registered
himci: mmc host probe
himci: mmc host probe
himci: mmc host probe
TCP: cubic registered
NET: Registered protocol family 10
NET: Registered protocol family 17
UBI: attaching mtd3 to ubi0
UBI: scanning is finished
UBI warning: print_rsvd_warning: cannot reserve enough PEBs for bad PEB handling, reserved 16, need 20
UBI: attached mtd3 (name "app", size 16 MiB) to ubi0
UBI: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
UBI: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
UBI: VID header offset: 2048 (aligned 2048), data offset: 4096
UBI: good PEBs: 128, bad PEBs: 0, corrupted PEBs: 0
UBI: user volume: 1, internal volumes: 1, max. volumes count: 128
UBI: max/mean erase counter: 1/0, WL threshold: 4096, image sequence number: 1792315136
UBI: available PEBs: 0, total reserved PEBs: 128, PEBs reserved for bad PEB handling: 16
UBI: background thread "ubi_bgt0d" started, PID 37
Freeing unused kernel memory: 1836K (c0523000 - c06ee000)

            _ _ _ _ _ _ _ _ _ _ _ _
            \  _  _   _  _ _ ___
            / /__/ \ |_/
           / __random: S01udev urandom read with 2 bits of entropy available
   /  -  _ ___
          / /  / /  / /
  _ _ _ _/ /  /  \_/  \_ ______
___________\___\__________________

[RCS]: /etc/init.d/S01udev
udev[45]: starting version 167
[RCS]: /etc/init.d/S80network
[RCS]: /etc/init.d/S90hibernate
[RCS]: /etc/init.d/S99custom
UBIFS: static UBI volume - read-only mode
UBIFS: mounted UBI device 0, volume 0, name "app", R/O mode
UBIFS: LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
UBIFS: FS size: 12443648 bytes (11 MiB, 98 LEBs), journal size 2412544 bytes (2 MiB, 19 LEBs)
UBIFS: reserved for root: 0 bytes (0 KiB)
UBIFS: media format: w4/r0 (latest is w4/r0), UUID 1C851D5F-B0FA-43B4-95AF-AAEA180A61B9, small LPT model
[00:00:04][VC-SYS-Daemon][VCSDaemonInitializer.cpp:54][INFO]: VC-SYS version v1.2.6-18-g1857204

[00:00:04][VC-SYS-Daemon][GPIOController.cpp:194][INFO]: Initialized peripherials for hw_type=1205
[00:00:04][VC-SYS-Daemon][LEDController.cpp:141][INFO]: Setting auto leds preset. ID = 2
[00:00:04][VC-SYS-Daemon][NetworkController.cpp:751][INFO]: Setting (1) as main interface. Old main interface is (-1)
yaffs: dev is 32505860 name is "mtdblock4" rw
yaffs: passed flags ""
[00:00:05][VC-SYS-Daemon][GPIOController.cpp:266][ERROR]: Invalid key name wps
flash_parse_bad_blocks: Skipping bad block at 0x00060000 (0x00060000)
flash_parse_bad_blocks: Skipping bad block at 0x00240000 (0x01940000)
flash_parse_bad_blocks: Skipping bad block at 0x04900000 (0x06000000)
[03:00:05][FWUPDATER][FWUpdater.cpp:183][INFO]: No files to restore from techjson
mount: mounting /dev/mmcblk0p1 on /mnt/mmc01 failed: No such file or directory
Initializing motor modules
mmz_start: 0x84000000, mmz_size: 192M
sh: can't open 'config_sensor.sh': No such file or directory
Module himedia: init ok
Hisilicon Media Memory Zone Manager
The module param setup_allocator is hisi 
hi_osal 1.0 init success!
hi3516cv300_base: module license 'Proprietary' taints kernel.
Disabling lock debugging due to kernel taint
load sys.ko for Hi3516CV300...OK!
load region.ko for Hi3516CV300...OK!
load vgs.ko for Hi3516CV300...OK!
load viu.ko for Hi3516CV300...OK!
ISP Mod init!
load vpss.ko for Hi3516CV300...OK!
load vou.ko for Hi3516CV300...OK!
load rc.ko ...OK!
load venc.ko ...OK!
load chnl.ko for Hi3516CV300...OK!
load vedu.ko ...OK!
load h264e.ko ...OK!
load h265e.ko ...OK!
load jpege.ko ...OK!
load ive.ko for Hi3516CV300...OK!
load hi_piris.ko OK!
load ai.ko OK!
load ao.ko OK!
load aenc.ko OK!
load adec.ko OK!
load acodec.ko for Hi3516CV300...OK!
insert audio
load hi_mipi driver successful!
Load hi_cipher.ko success. 
hirtc init ok. ver=Aug  5 2021, 13:02:42.
Hisilicon Watchdog Timer: 0.01 initialized. default_margin=60 sec (nodeamon= 1)
hiwtdg init ok. ver=Aug  5 2021, 13:02:43.
==== Your input Sensor type is imx307 ====
`
В чём может быть проблема? Заранее спасибо!

**Comment by doctor-dark** [comment]
Проблема состоит в том что для phy в dts жёстко указан адрес, в моём случае некорректный. Решением послужило удаление строки reg= <1> из /arch/arm/boot/dts/, что позволило ядру автоматически искать корректный адрес phy

**Comment by dimerr** [comment]
Fixed. f8d2d2de90ec470d58c100285b0c1c0f11a810a2
