### ISSUE TITLE
Improving Sigmastar support

### ISSUE THREAD

**Issue by NarkyAbyss** [OpenIPC/firmware#1641]
Recently got a IPCam with SSC337DE

I noticed a lot of the documentation is on Sigmastar SSC338Q. Specifically:
https://github.com/OpenIPC/wiki/blob/master/en/fpv-sigmastar.md

I'd like to attempt to run the IPL custom u-boot method mentioned.
How to build the image for 337DE?

@ZigFisher did you build the image? Can you help me document the process?

**Comment by flyrouter** [comment]
Good day
Thank you for your interest in our project.
Your processor is not relevant for working with FPV and we will not officially support it
You can take firmware images for video surveillance in the Firmware repository releases and in the Builder repository.
https://github.com/OpenIPC/firmware/releases/tag/image
https://github.com/OpenIPC/builder/releases/tag/latest
