### ISSUE TITLE
Некорректно работает ntp. Часы отстают на 1 час 5 минут

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/firmware#175]
Установлен корректный часовой пояс. При перезапуске камеры время всегда устанавливается на 1 час 5 минут назад и так и показывают все время. Если нажать кнопку синхронизировать с ntp то устанавливается корректное время. После перезапуска часы также сбиваются.
Во время работы автосинронизация с ntp не работает

**Comment by esuslik** [comment]
root@openipc-hi3516ev300:~# cat /etc/TZ 
<+05>-5

root@openipc-hi3516ev300:~# ps
PID   USER     COMMAND
    1 root     init
    2 root     [kthreadd]
    3 root     [ksoftirqd/0]
    5 root     [kworker/0:0H]
    7 root     [lru-add-drain]
    8 root     [kdevtmpfs]
    9 root     [kworker/u2:1]
  172 root     [oom_reaper]
  173 root     [writeback]
  175 root     [kcompactd0]
  176 root     [crypto]
  177 root     [bioset]
  179 root     [kblockd]
  182 root     [spi0]
  185 root     [spi1]
  186 root     [kworker/0:1]
  287 root     [rpciod]
  288 root     [xprtiod]
  295 root     [kswapd0]
  347 root     [nfsiod]
  399 root     [bioset]
  400 root     [bioset]
  401 root     [bioset]
  402 root     [bioset]
  403 root     [bioset]
  404 root     [bioset]
  405 root     [bioset]
  406 root     [bioset]
  407 root     [bioset]
  408 root     [bioset]
  409 root     [bioset]
  410 root     [bioset]
  411 root     [bioset]
  412 root     [bioset]
  413 root     [bioset]
  414 root     [bioset]
  448 root     [bioset]
  451 root     [bioset]
  453 root     [bioset]
  456 root     [bioset]
  459 root     [bioset]
  462 root     [bioset]
  465 root     [bioset]
  468 root     [bioset]
  480 root     [bioset]
  485 root     [bioset]
  490 root     [bioset]
  495 root     [bioset]
  500 root     [bioset]
  506 root     [kworker/u2:2]
  539 root     [irq/26-mmc0]
  545 root     [ipv6_addrconf]
  546 root     [kworker/0:2]
  554 root     [kworker/0:1H]
  561 root     [jffs2_gcd_mtd4]
  586 root     /sbin/syslogd -n -C64
  590 root     /sbin/klogd -n
  625 root     /usr/sbin/rngd -r /dev/urandom
  659 root     udhcpc -x hostname:openipc-hi3516ev300 -T 1 -t 5 -R -b -O search -p /var/run/udhcpc.eth0.pid -i eth0
  664 root     /usr/sbin/ntpd -n
  671 root     /usr/sbin/dropbear -R -B -k -p 22 -K 300
  673 root     /usr/sbin/httpd httpd -p 85 -f -c /etc/httpd.conf -r Authentication
  685 root     /usr/sbin/crond -f -c /etc/crontabs
  741 root     [irq/42-VI_CAP0]
  818 root     [hidog]
  822 root     /usr/bin/majestic -s
  823 root     /sbin/getty -L console 0 vt100
  966 root     /usr/sbin/dropbear -R -B -k -p 22 -K 300
  967 root     -sh
  976 root     ps

**Comment by esuslik** [comment]
так и выбрано, удалил поставил другой, и потом снова удалил и поставил корректный. Ничего не изменилось

**Comment by ZigFisher** [comment]
Ну вот напишите пожалуйста чётко, что было, что стало, что меняли..

**Comment by esuslik** [comment]
![изображение](https://user-images.githubusercontent.com/16290583/154787283-fa18ab81-55c9-4a89-b8e9-8240f31a14d0.png)
удалил екатеринбург, выбрал карачи, перезапустил
снова удалил карачи и выбрал екатеринбург. 
На фото как все отображется после перезапуска камеры. Часы отстают на 1 час 5 минут.

**Comment by ZigFisher** [comment]
Спасибо, теперь есть пример, как будет возможность постараюсь повторить и отпишусь.

**Comment by themactep** [comment]
Шальная мысль -- а нет ли в камере RTC с неверно зашитым временем?

**Comment by esuslik** [comment]
как это проверить?

**Comment by themactep** [comment]
![hi3516ev300](https://user-images.githubusercontent.com/37488/156061619-81a6a316-2851-4acb-9675-d4cf8cb3c772.png)

Поскольку у вас hi3516ev300, RTC там точно есть. Вопрос, как быстро появится поддержка его в OpenIPC. Недавно тема RTC на HiSilicon [всплыла на нашем Телеграм-канале](https://t.me/openipc_modding/133378). Там же есть документация из SDK, код и даже скомпилированный бинарник. Если у вас есть скил -- можете помочь.

**Comment by esuslik** [comment]
К сожалению скилов нет

**Comment by esuslik** [comment]
проблема решена путем обновления и сброса до завдоских настроек командой sysupgrade -k -r -n
