### ISSUE TITLE
Перестал работать onvif и rtsp при открытии в vlc на последней прошивке

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/firmware#176]
Перестал работать onvif и rtsp при открытии в vlc на последней прошивке
Оборудование
Процессор:hi3516ev300
Семейство:hi3516ev300
Сенсор:imx335_i2c
Флэш:16 MB
Температура:92.33°C
Прошивка
Версия:2.2.02.17-lite
Сборка:master+15bf5e0, 2022-02-17
majestic master+b4a1e57, 2022-02-16

**Comment by widgetii** [comment]
Please provide connection logs

**Comment by esuslik** [comment]
[majestic.core.txt](https://github.com/OpenIPC/firmware/files/8089763/majestic.core.txt)
[majestic.yaml.txt](https://github.com/OpenIPC/firmware/files/8089766/majestic.yaml.txt)
[majesticlog.log](https://github.com/OpenIPC/firmware/files/8089768/majesticlog.log)

**Comment by widgetii** [comment]
1) While software do you use to connect the camera?
2) Can you check RTSP connection by VLC and ffplay?

**Comment by esuslik** [comment]
через vlc картинку не прогружает, просто идет долгое подключение.
через облако ipeye таже история
регисратор на стоковой прошивке xm раньше подключался через onvif, теперь не подключается.

Подключение еще через несколько по по rtsp аботает
Подключение через netip тоже работает

**Comment by esuslik** [comment]
в новых версиях проблема решена
