### ISSUE TITLE
HeimVision HM311 (SSC335) …need some help!  

### ISSUE THREAD

**Issue by TMD-Burger** [OpenIPC/firmware#18]
Hello !
Can anybody help me to bring this "Puzzle" together?

I want to (re)flash the rootfs to the flash-chip (8MB).

**"bootlog(start)" ->**

`IPL 648312b
D-05
64MB
BIST0_0001-OK
Load IPL_CUST from NOR
MXP found at 0x00020000
offset:00010000
Checksum OK
IPL_CUSTg2cd6de2
MXP found at 0x00020000
runUBOOT()
[SPI_NOR]
 -Verify CRC32 passed!
 -Decompress XZ
  u32HeaderSize=0x00000040
  u32Loadsize=0x000178cc
  decomp_size=0x00040978
Disable MMU and D-cache before jump to UBOOTÌ
U-Boot 2015.01 (Jun 24 2020 - 11:37:44)
Version: I6g#######
I2C:   ready
DRAM:  
WARNING: Caches not enabled
MMC:   MStar SD/MMC: 0
nor_flash_mxp allocated success!!
Flash is detected (0x0707, 0xEF, 0x40, 0x17)
SF: Detected nor0 with total size 8 MiB
MXP found at mxp_offset[3]=0x00020000, size=0x1000
env_offset=0x4F000 env_size=0x1000
Flash is detected (0x0707, 0xEF, 0x40, 0x17)
SF: Detected nor0 with total size 8 MiB
In:    serial
Out:   serial
Err:   serial`

**bootloader-shell, "printenv" ->**

`baudrate=115200
bootargs=console=ttyS0,115200 root=/dev/mtdblock2 rootfstype=squashfs ro init=/linuxrc LX_MEM=0x3fc6000 mma_heap=mma_heap_name0,miu=0,sz=0x1770000
bootcmd=sf probe 0;sf read 0x22000000 0x50000 0x1f0000;bootm 0x22000000
bootdelay=0
ethact=sstar_emac
ethaddr=00:30:1b:ba:02:db
ipaddr=10.0.0.200
serverip=10.0.0.54
soc=ssc335
stderr=serial
stdin=serial
stdout=serial`

Now the Question:

How to (re)flash the rootfs? I have tried:

1.) setup a tftp-server (serverip) with "rootfs.squashfs.ssc335"-file (orginal-backup) 

2.) set env-variables:

`setenv soc ssc335
setenv ipaddr 10.0.0.200
setenv serverip 10.0.0.54
saveenv
`

3.) execute this command (idea from your "XM-Entry")

`sf probe 0; mw.b 0x22000000 ff 1000000; tftp 0x22000000 rootfs.squashfs.${soc} ;sf erase 0x220000 0x420000; sf write 0x22000000 0x220000 ${filesize}
`

I have a little problem to understand the "ram<->flash<->ram"-thing… (adresses, offsets, from/to)

Thank you :)

**Comment by ZigFisher** [comment]
Unfortunately, I had to postpone the work on this processor a little. I'll be back to work in the next few days. 
If during this time you have something interesting to share, we will always be happy. Thanks.
