### ISSUE TITLE
Is it support ipcam on xm550ai chip?

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/firmware#20]
and how to install firmware on ipcam xm550ai?

**Comment by ZigFisher** [comment]
https://github.com/OpenIPC/openipc-2.1/wiki/install_xm530

**Comment by esuslik** [comment]
Unfortunately i cannot understand. Which program i need to use and how to upload new firmware to ipcam.
Need step by step instruction

**Comment by widgetii** [comment]
You will need UART adapter connected to your computer and camera and then boot to U-boot command line and do commands applicable for your board.

Don't forget about backup of your original firmware

**Comment by esuslik** [comment]
i can't find uart interface on board. Maybe you can help?
[Parameters for IVG-85X50PYA-S.pdf](https://github.com/OpenIPC/openipc-2.1/files/6530231/Parameters.for.IVG-85X50PYA-S.pdf)

**Comment by widgetii** [comment]
![image](https://user-images.githubusercontent.com/6576495/119321883-c6634980-bc85-11eb-9f6c-1207342ddf71.png)

Check top connector with pin marked from 1 to 4, first find GND with your multimeter and then find TX and RX by trial and error method
