### ISSUE TITLE
Предложение. Несколько профилей конфигурации для освещённости светло/темно

### ISSUE THREAD

**Issue by vebmaster** [OpenIPC/firmware#206]
Здравствуйте.
Хочу предложить следующий функционал.
Камера (majestic) меняет профили/конфигурации в зависимости от освещённости.
Т.е. если я снимаю в цвете, то в цвете камера и продолжает снимать, но из-за слабой освещённости (при которой она бы перешла в режим ночь-чёрнобелый), камера меняет профиль с настройками для низкой освещённости.
Например вариант с 2 профилями светло/темно.
Зачем это надо: я заметил, что ночью при низкой освещённости (или наоборот днём при яркой) некоторые настройки могут негативно сказываться на качестве получаемой картинки с видеокамеры.
Например менять можно такие параметры как:  slowShutter, exposure, aGain, dGain, ispGain, drc, contrast, hue, saturation, luminance, drcOverride, fps, bitrate, gopSize.
И если настроить 2 профиля конфигурации для светло/темно, то можно получать наилучшую картинку для соответствующего режима камеры (светло/темно).
Т.е. не просто смена "цветной" на "ч\б", а смена почти целого профиля со своими настройками картинки.
Естественно настройки профиля должны быть только такими, которые не требуют перезагрузки маджестика (RTSP сервера), чтобы видеопоток не разрывался.

В телеграмме пишут, что это неактуально уже, но я считаю наоборот это более продвинутой конфигурацией камеры.

На примере сенсоров imx307 и imx335 замечаю, что если выкрутить настройки для наилучшей картинки в темноте в цвете, то когда выйдет солнце, картинка будет диаметрально плохой, засвеченной. Что даёт повод сделать как минимум 2 конфигурации для дня и ночи.

**Comment by vebmaster** [comment]
@katyo
> У вас прошивка работает нормально при низкой освещенности? Какой процессор?

Да, нормально. Только ваш вопрос немного не по теме обсуждения :) Лучше создать отдельный вопрос, если у вас проблемы какие то или добро пожаловать в чат телеграм: https://t.me/openipc_modding
Было как то что фпс проседал в темноте, когда я slowShutter изменял на любое значение, отличное от "disabled". После установки в "disabled" фпс в темноте перестал проседать.

**Comment by katyo** [comment]
Такой же конфиг, как у меня. Но в моём случае бесконечно перезагружается при недостатке освещения из-за того, что стример быстро съедает всю доступную память и система перестаёт сбрасывать watchdog.
Я создал вопрос в треккере majestic.

**Comment by widgetii** [comment]
Такую возможность планируется добавить в ближайшем будущем, как только будет получено достаточно отзывов о работе единого профиля в `isp.iqProfile`

**Comment by vebmaster** [comment]
> как только будет получено достаточно отзывов о работе единого профиля в `isp.iqProfile`

это в последних прошивках появилось? У меня щас декабрьская стоит, не в курсе такого.
