### ISSUE TITLE
Broken serial console in the SSC335 kernel

### ISSUE THREAD

**Issue by operutka** [OpenIPC/firmware#23]
This commit 7bc7d64f46604e497c20fec4e217f7bc89d02879 appears to break the serial console in the SSC335 kernel. The kernel gets loaded but there is no output. I'm not sure if it's just the console or the kernel is frozen. Anyway, if I build the previous revision (i.e. 2867d53e0174eb54a73d99cdb212517efc134072), the console works fine.

**Comment by ZigFisher** [comment]
Thank you so much for your feedback
In the near future, I will study this question and write the result here

**Comment by ch999dev** [comment]
@ZigFisher should be fixed by #25

**Comment by operutka** [comment]
I can confirm it's been fixed. Closing the issue.
