### ISSUE TITLE
Детекция движения с отправкой на email

### ISSUE THREAD

**Issue by esuslik** [OpenIPC/firmware#238]
Возможно реализовать детекцию движения с отправкой на email как на стоковых прощивках?
Есть облачные сервисы которые для экономии на ресурсах серверов перекладывают функцию детекции на камеру и принимают сигнализацию на email

**Comment by widgetii** [comment]
Если есть какой-то протокол, который поддерживается существующими серверами, то нужно его описание и методику, как (и на чем) тестировать его корректность

**Comment by esuslik** [comment]
на сколько я понял это стандартная реализация почтового клиента.
для примера скрины с двух камер. Это просто настройка с какого почтового сервера, куда отправить письмо и скакой темой и содержимым.
Тестировать возможно на обычном почтовом сервере, например на яндексе. 
![Screenshot_20220619_132947](https://user-images.githubusercontent.com/16290583/174472763-e03723f8-5c93-4b18-8951-a1cf0bbe56df.png)
![Screenshot_20220619_133332](https://user-images.githubusercontent.com/16290583/174472764-dbc37444-eea8-428e-843b-95e3e3017063.png)

**Comment by ZigFisher** [comment]
Отправку можно делать через имеющийся у нас в прошивке curl, он понимает почтовые протоколы и умеет SSL.
Это следующий этап для создания плагина от @themactep

**Comment by ZigFisher** [comment]
Добавлен плагин отправки снапшота на Email

**Comment by esuslik** [comment]
Плагин увидел, настроил. Но не понятно как к нему прикрутить детекцию, чтобы при движении в кадре, шла отправка на email

**Comment by themactep** [comment]
Маджестик умер или mjpeg отключен?

**Comment by esuslik** [comment]
отключен mjpeg был

**Comment by esuslik** [comment]
они у меня все отключены кроме rtsp, т.к. на них нет авторизации

**Comment by esuslik** [comment]
при нажатии на кнопку send to email что-то должно происходить?
Я вулючил mjpeg, картинка появилась. При нажатии send to email ничего не происходит

Также есть поозрение что фуекция send to mail не должна зависеть от mjpeg и т.п.
При детекции движения я так понммаю должно просто уходить пустое письмо с текстом что замечено движение.

**Comment by themactep** [comment]
для отсылки снэпа должен быть включен jpeg и настроена отсылка например на почту. проверить работоспособность настроек можно запустив /usr/sbin/send2email.sh из консоли. если есть ошибка, она там вылезет.

**Comment by esuslik** [comment]
Проверил на почту яндекс приходит письмо со снапшотом.
Есть возможность убрать вложение снапшота? или возможность отключать его отправку.
Кажется плагин send2email это должен быть только транспорт. А вот что уже отправлять мы бы выбирали в других плагинах типа детектор движения и внем уже ставить галку надо ли прикреплять вложение и какой текст сообщения.

Плагин motion detect ничего не отправляет. 
Запустил в консоли logread -f | grep "Motion detected in 3 regions" и там тишина, возможно детекто не не пишет события в лог?

**Comment by themactep** [comment]
Какая камера? Есть ли в ней аппаратная детекция движения?

**Comment by esuslik** [comment]
hi3516ev300 (hi3516ev300 family), imx335, 16 MB Flash, 2.2.07.25-lite

На стоковой прошивке работает. Не знаю аппаратная или нет. Но на картинке при включении детекции, видно квадратиками что детектит движения

**Comment by themactep** [comment]
Использование send2email для motion guard -- это частный случай. Это вполне самостоятельный плагин для отправки снэпшота на преднастроенную почту. Я не вижу смысла в том, чтобы убирать из письма картинку. И что тогда останется? Разверни мысль и приведи алгоритм использвования без картинки.

**Comment by themactep** [comment]
Запусти маджестик из консоли и посмотри, что будет в выводе при движении перед камерой. Может там синтаксис другой. Естественно, в настройках маждестика должна быть включена поддержка motion detection.

**Comment by esuslik** [comment]
Есть видеорегистратор который пишет архив. На нем можно подключить детекцию движения чтобы на ленте архива показывать участки где есть движение. 
Узнает он о том что было движение путем получения письма на email. И ему достаточно просто сообщения без вложений.
То есть если без картинки будет экономится место.
Если в камере не включен jpeg то на почту приходит битая картинка.

Если смотреть аналогию с камерами и стоковыми прошивками, то там много событий который можно детектить и отсылать по разным каналам связи.

Например детектор проблем с сд картой, при обнаружении отправить на email. Зачем тут картинка?
Детоктор проблемы с сетью, отправить после восстановления уведомление на email. Зачем тут картинка?
Детектор вообще любого события может быть, и не всегда нужно чтобы была картинка.

Понятно что такгого функционала пока нет, но  на будущее он может появиться.

**Comment by esuslik** [comment]
Но даже с картинкой сейчас при движении ничего не приходит на email. Где-то может можно логи посмотреть, почем не уходит или может нечему уходить?

**Comment by esuslik** [comment]
![изображение](https://user-images.githubusercontent.com/16290583/180923554-60e00e21-880a-44cf-af33-5eb391124714.png)

**Comment by themactep** [comment]
Запусти `/usr/sbin/send2email.sh` из консоли камеры. Если картинка приходит, значит нет вызова из парсера логов. Надо стартовать маждестик руками в консоли и отследить, шлет ли камера сигнал, что замечено движение. Вот пример сообщений с камеры:

```
Jul 25 18:41:25 openipc-hi3518ev200 user.debug majestic[958]: Motion detected in 1 regions, 1872x188 -> [1912x432]
Jul 25 18:41:25 openipc-hi3518ev200 user.debug majestic[958]: 1832,48  80,590
Jul 25 18:41:25 openipc-hi3518ev200 user.debug majestic[958]: 1896,702  16,172
Jul 25 18:41:25 openipc-hi3518ev200 user.debug majestic[958]: Motion detected in 2 regions, 1832x48 -> [1912x874]
Jul 25 18:41:25 openipc-hi3518ev200 user.debug majestic[958]: 1808,0  104,890
Jul 25 18:41:25 openipc-hi3518ev200 user.debug majestic[958]: 1616,998  72,40
Jul 25 18:41:25 openipc-hi3518ev200 user.debug majestic[958]: Motion detected in 2 regions, 1616x0 -> [1912x1038]
Jul 25 18:41:26 openipc-hi3518ev200 user.debug majestic[958]: 1776,0  136,882
Jul 25 18:41:26 openipc-hi3518ev200 user.debug majestic[958]: 1816,908  96,162
Jul 25 18:41:26 openipc-hi3518ev200 user.debug majestic[958]: 1616,998  40,40
Jul 25 18:41:26 openipc-hi3518ev200 user.debug majestic[958]: Motion detected in 3 regions, 1616x0 -> [1912x1070]
```

**Comment by themactep** [comment]
Детект есть. Осталось понять, почему не шлет. Какой содержимое файла, что создается при настройке детектора? Он там выводится рядом с формой.

**Comment by themactep** [comment]
После перезагрузки камеры `# ps | grep motion`, чтобы проверить, что созданные файл запущен. Вывод должен содержать строку типа `585 root     {S92motion} /bin/sh /etc/init.d/S92motion start`.

**Comment by esuslik** [comment]
![изображение](https://user-images.githubusercontent.com/16290583/180935548-2d0c73f5-6274-4be0-a82b-5a05d437143d.png)

**Comment by esuslik** [comment]
![изображение](https://user-images.githubusercontent.com/16290583/180935823-bf82dd66-040f-46f2-9e31-5757c18b20b6.png)

**Comment by esuslik** [comment]
Кстати если выставлять Sensitivity то осле применения всегда ползунок показывает значение 3, хотя в скрипте в конфиг файле стоит то которое применил.
То есть не понять какое значение sensivity стоит не понимая и расшифровывая конфиг файл

**Comment by esuslik** [comment]
Удалось протестировать отправку на yandex через yandex
Включил cli -s .system.logLevel debug

Сообщения пошли на ящик. Теперь осталоcm разобраться почему не корректно приходят на регистратор. Есть подозрение что где-то не подставляется поле  email_from_name или email_from_address

**Comment by themactep** [comment]
> Кстати если выставлять Sensitivity то осле применения всегда ползунок показывает значение 3, хотя в скрипте в конфиг файле стоит то которое применил. То есть не понять какое значение sensivity стоит не понимая и расшифровывая конфиг файл

в свежей версии должно выставлятся нужное значение на полозке.

**Comment by esuslik** [comment]
ползунок теперь работает кака надо.

Сообщения пошли на ящик. Теперь осталоcь разобраться почему не корректно приходят на регистратор. Есть подозрение что где-то не подставляется поле email_from_name или email_from_address

**Comment by themactep** [comment]
я добавил логи в сервисы отправки. будет легче обнаружить ошибку.

**Comment by esuslik** [comment]
# cat /tmp/webui/email.log
* response reading failed

Может где-то еще есть логи поподробнее?

**Comment by themactep** [comment]
Это ошибка SSL/TLS сертификата. Принимающая сторона точно умеет SSL? Сертификат валидный?

**Comment by esuslik** [comment]
не умеет, и в настройках плагина ssl отключен

**Comment by themactep** [comment]
тяни новый апдейт, там запись в лог команды, которая отправляет почту. будем разбирать ее.

**Comment by esuslik** [comment]
curl --verbose --silent --connect-timeout 100 --max-time 100 --user alert1@video.ru:1234321 --url smtp://app.3it.ru:1025 --mail-from CHE_6_001@video.ru --mail-rcpt alert2@video.ru -F '=(;type=multipart/mixed' -F "=Thu Jul 28 08:36:50 +05 2022;type=text/plain" -F "file=@/tmp/email_snap.jpg;type=image/jpeg;encoder=base64" -F '=)' -H "Subject: Snapshot from openipc-hi3516ev300" -H "From: \"CHE_6_001@video.ru\" <CHE_6_001@video.ru>" -H "To: \"alert2@video.ru\" <alert2@video.ru>"

* response reading failed

**Comment by themactep** [comment]
Во From и To имя в ковычках, которые должны быть экранированы. Это форматирование гитхаба съело слэши или вывод в консоли такой?

**Comment by themactep** [comment]
![IMG_20220728_053437](https://user-images.githubusercontent.com/37488/181473531-0191bd10-d6d8-45c4-bb0a-ae84e7354ac8.jpg)

**Comment by esuslik** [comment]
гитхаб съел. Кстати при включении плагина motionguard начинает падать маджестик.  Если перезапустить маджестик с консоли то не падает. Есть подозрение что дело в том что плагин начинает парсить логи и от этого что-то ломается.

![изображение](https://user-images.githubusercontent.com/16290583/181480222-d24e313f-19af-435f-9888-49ee1bf8646a.png)

**Comment by themactep** [comment]
А если зайти телнетом на app.3it.ru, порт 1025 и сэмулировать отправку письма, ошибки будут?
```
EHLO app.3it.ru
MAIL FROM: CHE_6_001@video.ru
RCPT TO: alert2@video.ru
QUIT
```

**Comment by esuslik** [comment]
не дает ничего сделать 
![изображение](https://user-images.githubusercontent.com/16290583/181488233-cd3ae959-85d2-4c10-a6df-2cb0663d571a.png)

**Comment by esuslik** [comment]
а нет, дает
![изображение](https://user-images.githubusercontent.com/16290583/181488441-adbfecf8-5a5c-4f0f-9f28-386a3851532a.png)

**Comment by themactep** [comment]
команды в телнете надо вводить руками построчно, получая после каждой ответ от сервера.

**Comment by esuslik** [comment]
не успею тогда, через несколько секунд связь обрывает

**Comment by themactep** [comment]
в шелле линукса:
`echo -e "EHLO app.3it.ru\nMAIL FROM: CHE_6_001@video.ru\nRCPT TO: alert2@video.ru\nQUIT" | nc app.3it.ru 1025`

**Comment by esuslik** [comment]
![изображение](https://user-images.githubusercontent.com/16290583/181675502-9e79dafa-c42f-4281-b41e-41b5e3983dec.png)

**Comment by themactep** [comment]
```
root@openipc-hi3518ev100:~# echo -e "EHLO app.3it.ru\nMAIL FROM: CHE_6_001@video.ru\nRCPT TO: alert2@video.ru\nQUIT" | nc mail.themactep.com 25
220 micro.themactep.com ESMTP Exim 4.96 Thu, 28 Jul 2022 23:49:23 -0400
250-micro.themactep.com Hello d192-186-103-98.static.comm.cgocable.net [192.186.103.98]
250-SIZE 52428800
250-8BITMIME
250-PIPELINING
250-PIPECONNECT
250-CHUNKING
250-STARTTLS
250-PRDR
250 HELP
250 OK
550 relay not permitted
221 micro.themactep.com closing connection
root@openipc-hi3518ev100:~#
```
Это пример того, как отвечает нормальный SMTP сервер.
Смотри логи на принимающей стороне.

**Comment by esuslik** [comment]
там нет логов, там закрытый регистратор. Суть в том что с камеры с ориг прошивкой работает как положено и с камеры dahua с ориг прошивкой тоже работает.
Разработчикам рега я отписался, они тоже будут смотреть

**Comment by esuslik** [comment]
Еще хотелось бы разобраться с падением маджестика, не знаю сюда это или нет. Вроде чюда т.к. падает при включении плагинов, а вроде и маджестик падает.
При включении плагина motionguard начинает падать маджестик. Если перезапустить маджестик с консоли то не падает. 
Причем когда падает маджести то он не отправляет корку на фтп и не пишет ее на саму камеру. И watchdog не всегда срабатывает.

**Comment by themactep** [comment]
> там нет логов, там закрытый регистратор. Суть в том что с камеры с ориг прошивкой работает как положено и с камеры dahua с ориг прошивкой тоже работает. Разработчикам рега я отписался, они тоже будут смотреть

Это Yucca что ли? Ну, они вчера форкнули репо, вроде начали что-то пилить для совместимости. Может чего родят.

**Comment by esuslik** [comment]
нет это другой

**Comment by themactep** [comment]
Маджестик вроде бы @widgetii пофиксил сегодня. В новой сборке должен приползти.

**Comment by esuslik** [comment]
обновился час назад, проблема с падением сохраняется

**Comment by widgetii** [comment]
1. На каждую проблему нужно открывать отдельный тикет, не нужно все мешать в кучу
2. В проблеме должно описываться как ее воспроизвести (шаг за шагом)

**Comment by esuslik** [comment]
так это понятно, я  об этом писал что проблема только при в ключении модуля в вебе который парсит логи. Поэтому пока не заводил отдельный тикет в реп маджестика. Ждал ответа по вебу может проблема тут и кроется, а не в маджестике. 
Тикет в маджестик сделаю, только ни логов ни корок не прикреплю, т.к. они не создаются.
