### ISSUE TITLE
Time in log without timezone...

### ISSUE THREAD

**Issue by khseal** [OpenIPC/firmware#283]
In the logs, time without a timezone.

**Comment by widgetii** [comment]
Please elaborate an issue you encountered

**Comment by khseal** [comment]
It was necessary to create a ticket in the web interface.
Example
Aug 14 09:18:35 openipc-hi3516dv100 user.info majestic[904]: New connection to IPEYE server
Realtime 12:18

**Comment by themactep** [comment]
Is timezone set up on the camera?

**Comment by khseal** [comment]
yes

**Comment by themactep** [comment]
is it a logread output?

**Comment by khseal** [comment]
Here
![image](https://user-images.githubusercontent.com/11374629/185236607-1cbb44fd-9451-431b-a36f-f15162a6aaba.png)

**Comment by themactep** [comment]
yes, right. logread time is UTC.

**Comment by themactep** [comment]
Fixed.
