### ISSUE TITLE
New feature request: publish my camera button

### ISSUE THREAD

**Issue by carbofos** [OpenIPC/firmware#295]
Если в теории это возможно, было бы хорошо чтобы внутри HLS использовался .ts вместо .mp4 .
Так контент сможет воспроизводится на телевизорах.

Тогда можно будет сделать в вебинтерфейсе кнопку "опубликовать мою камеру в каталоге" и она через онлайн сервис будет добавляться в публичнодоступный live.m3u8 чтобы можно смотреть обуликованные камеры на TV, подключив m3u8.
Скажем, создать нечто вроде http://www.insecam.org  .

**Comment by widgetii** [comment]
Поддержка .ts не планируется (за исключением варианта, если найдется спонсор, который будет готов профинансировать данную фичу)
