### ISSUE TITLE
нет драйвера в /lib/

### ISSUE THREAD

**Issue by iSetebos** [OpenIPC/firmware#440]
Процессор T31n. Нет драйвера для WiFi чипа mt7601.
![Wifi](https://user-images.githubusercontent.com/36000949/188875659-4b964cdc-2b66-4342-8159-ebab4359d22a.jpg)

**Comment by ZigFisher** [comment]
Из-за своего огромного размера, если собирать как модуль, размера он сразу вкомпилен в ядро
