### ISSUE TITLE
ONVIF button in disabled state in web interface does not disable ONVIF

### ISSUE THREAD

**Issue by carbofos** [OpenIPC/firmware#442]
В вебинтерфейсе кнопка отключения onvif не дает отключения этого протокола по факту.
Рег все равно получает свои ответы. Но если включить и выключить, чтобы в majestic.yaml появилась запись onvif.enabled=false, тогда уже отключает.

**Comment by themactep** [comment]
Нет, не так.

Вот дефолный конфиг, изменений нет:

![Screenshot from 2022-09-08 21-21-17](https://user-images.githubusercontent.com/37488/189252623-22ba6b68-a7e1-444f-97cf-95da0871ea16.png)

При открытии этой формы веб запрашивает у yaml-cli состояние onvif в конфиге; yaml-cli отвечает, что у него нет данных:
```
root@openipc-hi3518ev100-web:~# yaml-cli -g .onvif.enabled
root@openipc-hi3518ev100-web:~# 
```
Т.е. значение onvif.enabled находится в квантовой суперпозиции. Но веб считает все не однозначно включеное выключеным и рисует переключатеть в положении "выключено".

![Screenshot from 2022-09-08 21-21-35](https://user-images.githubusercontent.com/37488/189252624-5ea67038-5a72-4a7b-98ef-b5ed2fc99e8f.png)

Здесь я нажимаю кнопку "Save Changes" даже не меняя положение переключателя.

![Screenshot from 2022-09-08 21-21-48](https://user-images.githubusercontent.com/37488/189252625-18b462ab-558c-4b0b-ba1d-51126edcf3a0.png)

В конфиг записан параметр для onvif - не включать.

![Screenshot from 2022-09-08 21-22-07](https://user-images.githubusercontent.com/37488/189252626-47a64a6a-8d88-4218-815f-aed64855eb74.png)

После чего дается команда на перечитывание конфига маджестиком.

https://github.com/OpenIPC/microbe-web/blob/d6ab350f55220920667eda958d04e4afe62a8d81/files/var/www/cgi-bin/majestic-settings.cgi#L74

Если что-то работает -- давайте разбираться по шагам.

**Comment by longcat99** [comment]
Maybe you should reset the config file.  I have encountered this situation, because I flashed other firmware and caused the configuration file to be wrong, some settings did not take effect.
