### ISSUE TITLE
Majestic should idle when there's no connection(s)

### ISSUE THREAD

**Issue by brainstorm** [OpenIPC/firmware#483]
While wondering why the camera was getting a bit hotter compared to stock firmware I realized that Majestic is quite busy under the hood ` 08:45:30 up 16:23,  load average: 1.56, 1.57, 1.58` (42degC with `majestic` running vs 36degC killing the process):

![image](https://user-images.githubusercontent.com/175587/192080861-f53e5229-10a5-4ab8-a2f7-e4b51b123803.jpeg)

![image](https://user-images.githubusercontent.com/175587/192080869-d84a3748-6729-4b5e-bc95-e1a2fb5da0dc.jpeg)

```
  698     2 root     DW       0   0%   5% [apical_isp_fw_p]
  692     1 root     S    45288 132%   0% /usr/bin/majestic -s
  571     1 root     S     2092   6%   0% wpa_supplicant -B -D wext -i wlan0 -c /etc/wpa_supplicant.conf
 1338  1337 root     S     1904   6%   0% /bin/sh
 1497  1338 root     S     1904   6%   0% /bin/sh
  536     1 root     S     1820   5%   0% /usr/sbin/rngd -r /dev/urandom
  501     1 root     S     1808   5%   0% /sbin/syslogd -n -C64 -t
  733   732 root     S     1784   5%   0% -sh
 1336   607 root     S     1756   5%   0% /usr/sbin/httpd httpd -p 85 -f -c /etc/httpd.conf -r Authentication
 1498  1338 root     S     1748   5%   0% sed s/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g;s/"/\&quot;/g
    1     0 root     S     1744   5%   0% init
  597     1 root     S     1744   5%   0% /usr/sbin/ntpd -n
  619     1 root     S     1744   5%   0% /usr/sbin/crond -f -c /etc/crontabs
  691     1 root     S     1744   5%   0% /sbin/getty -L console 0 vt100
  590     1 root     S     1744   5%   0% udhcpc -x hostname:openipc-t10 -T 1 -t 5 -R -b -O search -p /var/run/udhcpc.wlan0.pid -i wlan0
  607     1 root     S     1744   5%   0% /usr/sbin/httpd httpd -p 85 -f -c /etc/httpd.conf -r Authentication
  505     1 root     S     1740   5%   0% /sbin/klogd -n
 1502  1497 root     S     1740   5%   0% head -20
 1501  1497 root     S     1740   5%   0% sed 1,4d
  732   602 root     S     1124   3%   0% /usr/sbin/dropbear -R -B -k -p 22 -K 300 -2
```

And that's when there's no active clients:

```
root@openipc-t10:~# netstat -tunl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:34567           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:554             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 :::554                  :::*                    LISTEN
tcp        0      0 :::85                   :::*                    LISTEN
tcp        0      0 :::22                   :::*                    LISTEN
udp        0      0 0.0.0.0:34569           0.0.0.0:*
udp        0      0 0.0.0.0:3702            0.0.0.0:*
udp        0      0 0.0.0.0:50105           0.0.0.0:*
udp        0      0 0.0.0.0:55239           0.0.0.0:*
udp        0      0 0.0.0.0:5353            0.0.0.0:*
udp        0      0 0.0.0.0:33007           0.0.0.0:*
```

Ideally Majestic should sleep or reduce its load when not actively used?

**Comment by widgetii** [comment]
T10 is in MVP stage, a lot of work should be done to make it close to original firmware

**Comment by brainstorm** [comment]
Temperatures are starting to get fairly high with continuous use. It stopped responding the other day and the front lens assembly was almost too hot to the touch. Luckily the li-ion battery is cool and only the Ingenic processor and surrounding circuitry seems to be getting (too) hot.

On a second look, it seems like Majestic is barely consuming ~5% of CPU time, contrasting with 132% of VSZ, which is memory. 

So I wonder where does this relatively high load average come from? I guess that Majestic's size makes the OS have to swap/context switch constantly to accommodate it to the available memory and that's the root cause of the camera getting hotter than stock?

![IMG_0006](https://user-images.githubusercontent.com/175587/205434668-28841645-0c7c-4d1b-a17c-f3ac1d7a893c.JPG)
![IMG_0003](https://user-images.githubusercontent.com/175587/205434671-75542c5f-87c9-40ea-a06c-10b6a17756e2.JPG)
![IMG_0005](https://user-images.githubusercontent.com/175587/205434669-3c9e5a92-9039-4a14-b1d4-7c3f3bb9280e.JPG)
![IMG_0008](https://user-images.githubusercontent.com/175587/205434665-87a3d363-52af-4036-8700-e580c9191c79.JPG)

**Comment by widgetii** [comment]
Cannot comment on this one because we don't have such hardware, so nothing to investigate. I'm going to close this issue until someone donate it

**Comment by brainstorm** [comment]
This issue should be moved to the majestic repo accordingly, like this issue:

https://github.com/OpenIPC/majestic/issues/77
