### ISSUE TITLE
HI3516AV100 отсутствует eth0

### ISSUE THREAD

**Issue by mixatronik** [OpenIPC/firmware#502]
В новых сборках HI3516AV100 отсутствует eth0  на камере  DS-2CD2345F-IS. Куда копать?

**Comment by widgetii** [comment]
Если в старых все работало, но нужно искать когда и чем сломалось

**Comment by mixatronik** [comment]
К сожалению, при попытке прошить православный бут камера окирпичилась и было это в конце мая. Последняя из рабочих сборок, что у меня сохранились - от 27.05.22 9:30. Другая аналогичная камера появилась только теперь и проблема проявилась. Вот такая вот вилка.
Если есть какой-то архив, то готов оттестировать все, что между маем и октябрём, чтобы понять, на какой сломалось.

**Comment by widgetii** [comment]
Все архивы хранятся в [dev канале](https://t.me/s/openipc_dev). Чтобы сократить число попыток, воспользуйтесь бинарным поиском

**Comment by ZigFisher** [comment]
> В новых сборках HI3516AV100 отсутствует eth0 на камере DS-2CD2345F-IS. Куда копать?

Необходимо в переменных extras и bootargs U-boot выставить правильные значения.

**Comment by mixatronik** [comment]
> Все архивы хранятся в [dev канале](https://t.me/s/openipc_dev). Чтобы сократить число попыток, воспользуйтесь бинарным поиском

про дихотомию в курсе :)

**Comment by mixatronik** [comment]
> > В новых сборках HI3516AV100 отсутствует eth0 на камере DS-2CD2345F-IS. Куда копать?
> 
> Необходимо в переменных extras и bootargs U-boot выставить правильные значения.

как узнать какие? и extras у меня вообще нет.

**Comment by mixatronik** [comment]
Нашёл - в сборке от 31.07.22 интерфейс eth0 присутствует, а в сборке от 1.08.22 его уже нет. Что-то ещё нужно? Лог загрузки может быть?

**Comment by widgetii** [comment]
Под дату и описание подходит [этот коммит](https://github.com/OpenIPC/firmware/commit/2a757c3a1901f425c8e9f22c204872b2b95cc670)

**Comment by ZigFisher** [comment]
На части плат автодетект не работает, по-этому отключено.

**Comment by mixatronik** [comment]
что и где прописать для инициализации eth0?

**Comment by mixatronik** [comment]
Проблема локализована. Есть рабочая сборка и идёт работа над тем, как сделать так, чтобы работало у всех.
