### ISSUE TITLE
Out of memory  Hi3516EV300+imx335 

### ISSUE THREAD

**Issue by norulers** [OpenIPC/firmware#505]
Compile firmware tips with the latest OpenIPC 10-7
Out of memory: Kill process 879 (wfb_tx) score 33 or sacrifice child
Killed process 879 (wfb_tx) total-vm:6624kB, anon-rss:208kB, file-rss:4028kB, shmem-rss:0kB

By the way, what version of WFB ng does the current FPV firmware support.
Compatible [22.09-rc4-rpi3.img.gz] ？
Gstreamer How to adjust the command.

Error running default command on raspberry pi
gst-launch-1.0 -vvv udpsrc port=5600 ! application/x-rtp,encoding-name=H265,payload=96 ! rtph265depay ! h265parse ! queue ! avdec_h265 ! autovideosink sync=false -e

**Comment by cronyx** [comment]
connect to camera via ssh and run this commands:

```
fw_setenv osmem 64M
set_allocator cma
reboot
```
