### ISSUE TITLE
UPNP support required

### ISSUE THREAD

**Issue by carbofos** [OpenIPC/firmware#531]
Я столкнулся со следующей проблемой. Провайдеры как правило не дают возможность выставить нужный порт форвардинг на роутере для того чтобы сделать доступной камеру в интернете снаружи. Но обычно на рутерах включен серис UPNP, который позволяет запросить нужный порт, указав на какой IP внутри сети забрасывать трафик. Для линукса чтобы воспользоваться этим сервисом есть пакет miniupnpc.

Было бы чудесно, если бы OpenIPC поддерживала клиент UPNP из коробки. Это решит задачу доступа к камере снаружи, которая находится внутри локалки. При этом, очень желательно иметь возможность выбрать какие порты стоит выставлять, а какие нет: 22, 80, 85, 554.

**Comment by widgetii** [comment]
miniupnpc прямо сейчас доступен в ultimate в связи с отсутствием для него места в lite
