### ISSUE TITLE
Building u-boot-t20

### ISSUE THREAD

**Issue by moosehadley** [OpenIPC/firmware#601]
u-boot-t20 does not have any documentation on how it should be built.

It appears to require GCC3 or 4, which are very difficult to find with mips cross-compile.

Forcing it to use GCC5 or 10 causes errors.

Surely I'm missing something, how is this supposed to be built?

**Comment by themactep** [comment]
Issues is not  the right place for asking questions on building stuff. Please use one of a suitable telegram channels https://openipc.org/our-channels
