### ISSUE TITLE
Incorrect behavior for daemon restart

### ISSUE THREAD

**Issue by pianist** [OpenIPC/firmware#609]
* Camera board id: any (hi3518cv100)
 * OpenIPC version: 2.3.01.03-lite

Something wrong with majestic daemonization.

Steps to reproduce:
 * Log in (ssh) to system
 * do majestic restart
 * log out

Expectations: daemons continues to work.

Real life: daemon exits, logread line:

```
Jan 11 16:38:49 XXX-openipc authpriv.info dropbear[15099]: Exit (root) from <192.168.88.201:57134>: Keepalive timeout

```

**Comment by themactep** [comment]
is this still relevant?
