### ISSUE TITLE
Does fpv support h265?

### ISSUE THREAD

**Issue by zhuwei** [OpenIPC/firmware#651]
set drone-majestic.yaml:
`video0:
  enabled: true
  bitrate: 4096
  codec: h265
  rcMode: cbr
  gopSize: 0.2
  size: 1920x1080
`

How should the ground  be modified? Or don't need to modify it?

**Comment by widgetii** [comment]
You need to modify h264 to h265 on your ground station side (probably install all specific h.265 gstreamer plugins/codecs/libraries first)
