### ISSUE TITLE
[FR] gk7205v200 /v300 u-boot breaking only ctrl+c

### ISSUE THREAD

**Issue by whoim2** [OpenIPC/firmware#675]
This is very important for FPV topics. If the camera restarts in flight, for example, by watchdog, then the UART telemetry will stop loading the y-boot and the camera will freeze until the power is reset. Interrupting on e.g. Сtrl+С should solve this problem.

**Comment by FlyRouter** [comment]
You need to collect at least 10 signatures for this feature. 
Your colleagues need to sign here and then it will be implemented.

**Comment by kobzzon** [comment]
yes, I really need this project!

**Comment by Haker-che** [comment]
Implement it, wait!

**Comment by Ed1975I** [comment]
Yes, it is very necessary

**Comment by FlyRouter** [comment]
I forgot to add...
Accounts created no later than March 15 can participate in the voting...

**Comment by themactep** [comment]
I think limiting key combination to Ctrl-C would be beneficial for any platform, regardless FPV or not. My 2 cents.

**Comment by Ra3eR63** [comment]
Очень нужный проект!

**Comment by Platidors** [comment]
I really need it

**Comment by AlexPotatoKun** [comment]
Nice idea, really need it not only for FPV

**Comment by vbond-app** [comment]
it is important feature for FPV mode

**Comment by zhuwei** [comment]
I really need it!
gk7205v300, What is the minimum latency for 1080P FPV?

**Comment by whoim2** [comment]
> I really need it! gk7205v300, What is the minimum latency for 1080P FPV?
At v200 about 200-250ms. Go to "sandbox-fpv" repo and join to us tg group.

**Comment by dimerr** [comment]
[u-boot-gk7205v200-universal.zip](https://github.com/OpenIPC/firmware/files/11014202/u-boot-gk7205v200-universal.zip)

**Comment by whoim2** [comment]
im sorry, but
```
 flashcp -v /tmp/u-boot-gk7205v200-universal.bin /dev/
mtd0
Erasing block: 4/4 (100%)
Writing kb: 248/248 (100%)
Verifying kb: 248/248 (100%)
```
```
Hit any key to stop autoboot:  0
OpenIPC #
```

**Comment by whoim2** [comment]
thanks! this worked u-boot at https://github.com/OpenIPC/sandbox-fpv/tree/master/gk7205v200

**Comment by zhuwei** [comment]
> 

"fast 720p@50 "What is it? I don't understand. Can you explain it?

**Comment by zhuwei** [comment]
@whoim2 "fast 720p@50 "What is it? I don't understand. Can you explain it?

**Comment by whoim2** [comment]
> @whoim2 "fast 720p@50 "What is it? I don't understand. Can you explain it?

50fps > 30fps )

**Comment by whoim2** [comment]
> > > I really need it! gk7205v300, What is the minimum latency for 1080P FPV?
> > 
> > 
> > At v200 about 180-230ms. Go to "sandbox-fpv" repo and join to us tg group.
> 
> Is the group name OpenIPC (EN)?
https://openipc.org/our-channels
Try fpv (ru)
