### ISSUE TITLE
hi3516cv300: OpenIPC not provide autodetect sensor feature for majestic

### ISSUE THREAD

**Issue by DeeKey** [OpenIPC/firmware#68]
After upgrade from OpenIPC 1.0 on hi3516cv300 to OpenIPC 2.1 majestic did not autodetect sensor.
That is why majestic is not able to start streaming the video.

User has to manually add sensor to environment . In my case:

`fw_setenv sensor imx291_i2c_lvds`

Please update OpenIPC scripts so that freshly installed system will be able to provide sensor autodetection function for majestic.

**Comment by ZigFisher** [comment]
Thanks for the ticket
This is planned to be done in future versions

**Comment by widgetii** [comment]
Tested against current version on 

```
hardware=50H20L
devid=00022520
```

board via Coupler, everything works seamlessly
