### ISSUE TITLE
Sysupgrade should not upgrade kernel or rootfs if they were not changed

### ISSUE THREAD

**Issue by DeeKey** [OpenIPC/firmware#72]
Currently **sysupgrade** updates both kernel and rootfs even if they were not changed.
It takes time, degrades flash and poses risk if something will go wrong during the process.

**Proposal:**
 Improve **sysupgrade** so that it will check if upgrade of kernel or rootfs really needed.
Yet to add **-f** key to force upgrade.

**Comment by vebmaster** [comment]
I support adding the -f switch to force the update

**Comment by p0isk** [comment]
Added option -r / --rootfs, -k / --kernel for selective update

**Comment by p0isk** [comment]
Done.
Keys -f / --force also added

**Comment by ZigFisher** [comment]
Thanks to all
