### ISSUE TITLE
which Hi3516Ev300 board is best for OpenIPC?

### ISSUE THREAD

**Issue by catkira** [OpenIPC/firmware#728]
I want to by a Hi3516Ev300 board that works well with OpenIPC. So far my main candidates are
https://de.aliexpress.com/item/1005002294020685.html
https://de.aliexpress.com/item/1005002345471331.html
The PCBs look quite different on the front and back
first link PCB:
![image](https://user-images.githubusercontent.com/13425558/232307133-e555d3dc-f5fd-43c4-b7a4-20b6e5e2a20b.png)
![image](https://user-images.githubusercontent.com/13425558/232307164-4145eac7-18b0-4f5e-a7ed-c64a9cd7ddbe.png)
second link PCB:
![image](https://user-images.githubusercontent.com/13425558/232307113-1973ddfb-06bf-4606-83f6-4f4fb0090d1c.png)
![image](https://user-images.githubusercontent.com/13425558/232307189-b9d8bc15-2a22-4694-bafb-2c0203d28a3e.png)

which do You think is best? Or can You recommend even another one?

**Comment by catkira** [comment]
The 2nd one has an additional connector (P4) with debug signals, that seems to be an advantage.

**Comment by catkira** [comment]
https://www.xiongmaitech.com/en/index.php/product/product-detail/185/187/377
this is the manufacturer of the 2nd module

**Comment by catkira** [comment]
This is another variant
https://pt.aliexpress.com/item/1005002304736662.html

**Comment by cronyx** [comment]
> https://www.xiongmaitech.com/en/index.php/product/product-detail/185/187/377 this is the manufacturer of the 1st module

This is a good option, but the hi3516ev300 chips have been out of production for a long time, their counterpart is GK7205v300. https://www.xiongmaitech.com/en/index.php/product/product-detail/185/187/465
