### ISSUE TITLE
How to build nand rootfs for Hi3516CV500

### ISSUE THREAD

**Issue by TalusL** [OpenIPC/firmware#766]
How to build nand rootfs for Hi3516CV500？

**Comment by widgetii** [comment]
Use other platforms with NAND support like 3516cv300 or 3516av200 to study how to enable ubifs in configs

**Comment by TalusL** [comment]
> Use other platforms with NAND support like 3516cv300 or 3516av200 to study how to enable ubifs in configs

I modified the broad config and rebuilt it.Then I got the rootfs.ubi and rootfs.ubifs .But the  kernel does not find rootfs while booting and  reboot after 20 seconds.Something wrong？

**Comment by widgetii** [comment]
I suggest reading books about this topic (`Chris Simmonds, Mastering Embedded Linux` is the best choice from my point of view), then continue reading project's documentation
