### ISSUE TITLE
Wifi MT 7601 how to?

### ISSUE THREAD

**Issue by Haxerall** [OpenIPC/firmware#867]
Как настраивать wifi в камерах на openipc. Совершенно нет внятных инструкций хотя бы на конкретные чипы.

Если с ethernet мы хотя бы сразу получаем линк и доступ к ssh и веб интерфейсу. То когда  камера только с wifi без uart вообще ничего не получится сделать.

Как запускать wifi на 7601? Какие конфиги прописывать?

https://pastebin.com/gGdjwAg1

**Comment by Haxerall** [comment]
https://pastebin.com/aBn5tEh2

**Comment by themactep** [comment]
Issues - это не то место, где надо задавать вопросы. Для вопросов есть группы в телеграме https://openipc.org/our-channels
Проблема с mt7601 сейчас решается. Новый билд будет готов через несколько часов.
