### ISSUE TITLE
Wi-Fi mt7601u error found in Ingenic T31x lite

### ISSUE THREAD

**Issue by IPC-Probe** [OpenIPC/firmware#934]
I would like to test the Wifi-feature with T31x lite firmware that with both Ethernet and wireless connection.

first i connected MT7601U module D+/D-/GND to the Ingenic Snipe board micro usb port and providing 3,3V DC. 
with the putty i set the command - 
"**fw_setenv wlandev mt7601-t31-camhi**" 
and assigned wlanssid and wlanpass.

however after reboot, the system does not get any IP address in wlan0. and i dont find mt7601u with my mobile phone WiFi.
i type lsusb and read "Bus 001 Device 006: ID 148f:7601". 
so the mt7601u is detected by the system, right?

from the dmesg log.
it shows - < **ERROR!!! MT7601 E2PROM: WRONG VERSION 0xc, should be 9** >

and i found below from the file system
**/lib/firmware/mediatek/mt7601u.bin
/lib/firmware/mt7601u.bin**

please advise the correct procedures to add the WiFi mt7601u in T31x firmware.
any suggestion or extra information is helpful.

many thanks.

**Comment by themactep** [comment]
please provide more of dmesg log, not just the error line.

**Comment by IPC-Probe** [comment]
Hi Paul,

Thanks for your quick reply.
I probably send the whole log next Monday.





在 2023年8月5日週六 00:14，Paul Philippov ***@***.***> 寫道：

**Comment by IPC-Probe** [comment]
hi Paul.
below is the full bootup log. it seems that the IP cam can get the IP address from router now. (10.10.100.84)
**however it is not able to enter the web page or stream the video.** 

[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.10.14__isvp_swan_1.0__ (builder@citadel) (buildroot-gcc-12.2.0) #2 PREEMPT Mon Jul 24 22:29:42 MSK 2023
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 RESET ERROR PC:080C101D
[    0.000000] CPU0 revision is: 00d00100 (Ingenic Xburst)
[    0.000000] FPU revision is: 00b70000
[    0.000000] cgu_get_rate, parent = 1392000000, rate = 0, m = 129, n = 255, reg val = 0x081000ff
[    0.000000] cgu_get_rate, parent = 1392000000, rate = 0, m = 129, n = 255, reg val = 0x081000ff
[    0.000000] CCLK:1392MHz L2CLK:696Mhz H0CLK:200MHz H2CLK:200Mhz PCLK:100Mhz
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 0053a000 @ 00010000 (usable)
[    0.000000]  memory: 00036000 @ 0054a000 (usable after init)
[    0.000000] User-defined physical RAM map:
[    0.000000]  memory: 04000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x00000000-0x03ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x00000000-0x03ffffff]
[    0.000000] On node 0 totalpages: 16384
[    0.000000] free_area_init_node: node 0, pgdat 80548030, node_mem_map 81000000
[    0.000000]   Normal zone: 128 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 16384 pages, LIFO batch:3
[    0.000000] Primary instruction cache 32kB, 8-way, VIPT, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 8-way, VIPT, no aliases, linesize 32 bytes
[    0.000000] pls check processor_id[0x00d00100],sc_jz not support!
[    0.000000] MIPS secondary cache 128kB, 8-way, linesize 32 bytes.
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists in Zone order, mobility grouping off.  Total pages: 16256
[    0.000000] Kernel command line: mem=64M rmem=64M@0x4000000 console=ttyS1,115200n8 panic=20 root=/dev/mtdblock3 rootfstype=squashfs init=/init mtdparts=jz_sfc:256k(boot),64k(env),3072k(kernel),10240k(rootfs),-(rootfs_data)
[    0.000000] PID hash table entries: 256 (order: -2, 1024 bytes)
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Memory: 58896k/65536k available (4006k kernel code, 6640k reserved, 1342k data, 216k init, 0k highmem)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000] NR_IRQS:358
[    0.000000] clockevents_config_and_register success.
[    0.000014] Calibrating delay loop... 1391.00 BogoMIPS (lpj=6955008)
[    0.087831] pid_max: default: 32768 minimum: 301
[    0.092688] Mount-cache hash table entries: 512
[    0.097593] Initializing cgroup subsys debug
[    0.101849] Initializing cgroup subsys freezer
[    0.107258] devtmpfs: initialized
[    0.111998] regulator-dummy: no parameters
[    0.116368] NET: Registered protocol family 16
[    0.123843] Skipping MSC1_PB GPIO setup
[    0.127722] Skipping WYZE GPIO setup
[    0.131269] Skipping WYZE GPIO setup
[    0.135480] set gpio strength: 32-2
[    0.135489] set gpio strength: 33-2set gpio strength: 34-2
[    0.135498] set gpio strength: 35-2set gpio strength: 36-2
[    0.135506] set gpio strength: 37-2set gpio pull: 59-90
[    0.153316] bio: create slab <bio-0> at 0
[    0.163126] jz-dma jz-dma: JZ SoC DMA initialized
[    0.169389] usbcore: registered new interface driver usbfs
[    0.175366] usbcore: registered new interface driver hub
[    0.180879] usbcore: registered new device driver usb
[    0.186426]  (null): set:249  hold:250 dev=100000000 h=500 l=500
[    0.194111] Switching to clocksource jz_clocksource
[    0.201326] dwc2 otg probe start
[    0.201353] jz-dwc2 jz-dwc2: cgu clk gate get error
[    0.206333] DWC IN OTG MODE
[    0.210038] dwc2 dwc2: Keep PHY ON
[    0.213407] dwc2 dwc2: Using Buffer DMA mode
[    0.217735] dwc2 dwc2: Core Release: 3.00a
[    0.222016] dwc2 dwc2: DesignWare USB2.0 High-Speed Host Controller
[    0.228309] dwc2 dwc2: new USB bus registered, assigned bus number 1
[    0.235745] hub 1-0:1.0: USB hub found
[    0.239558] hub 1-0:1.0: 1 port detected
[    0.243557] dwc2 dwc2: DWC2 Host Initialized
[    0.247840] dwc2 otg probe success
[    0.248080] NET: Registered protocol family 2
[    0.252942] TCP established hash table entries: 512 (order: 0, 4096 bytes)
[    0.259956] TCP bind hash table entries: 512 (order: -1, 2048 bytes)
[    0.266328] TCP: Hash tables configured (established 512 bind 512)
[    0.272700] TCP: reno registered
[    0.275894] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.281856] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.288358] NET: Registered protocol family 1
[    0.292953] RPC: Registered named UNIX socket transport module.
[    0.298880] RPC: Registered udp transport module.
[    0.303694] RPC: Registered tcp transport module.
[    0.308416] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.315530] freq_udelay_jiffys[0].max_num = 10
[    0.320019] cpufreq udelay loops_per_jiffy
[    0.324377] dwc2 dwc2: ID PIN CHANGED!
[    0.328203] 12000 59956 59956
[    0.331458] 24000 119913 119913
[    0.334876] 60000 299784 299784
[    0.338318] 120000 599569 599569
[    0.341932] 200000 999282 999282
[    0.345383] 300000 1498924 1498924
[    0.349193] 600000 2997848 2997848
[    0.352821] 792000 3957159 3957159
[    0.356529] 1008000 5036385 5036385
[    0.360357] 1200000 5995696 5995696
[    0.373813] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.380926] jffs2: version 2.2. 穢 2001-2006 Red Hat, Inc.
[    0.386974] msgmni has been set to 115
[    0.392024] io scheduler noop registered
[    0.395952] io scheduler cfq registered (default)
[    0.407451] jz-uart.1: ttyS1 at MMIO 0x10031000 (irq = 58) is a uart1
[    0.415077] console [ttyS1] enabled, bootconsole disabled
[    0.434810] brd: module loaded
[    0.442451] loop: module loaded
[    0.445925] logger: created 256K log 'log_main'
[    0.452674] jz TCU driver register completed
[    0.458004] the id code = c84018, the flash name is GD25Q127C
[    0.464166] JZ SFC Controller for SFC channel 0 driver register
[    0.470464] 5 cmdlinepart partitions found on MTD device jz_sfc
[    0.476571] Creating 5 MTD partitions on "jz_sfc":
[    0.481570] 0x000000000000-0x000000040000 : "boot"
[    0.487522] 0x000000040000-0x000000050000 : "env"
[    0.493493] 0x000000050000-0x000000350000 : "kernel"
[    0.499776] 0x000000350000-0x000000d50000 : "rootfs"
[    0.505904] 0x000000d50000-0x000001000000 : "rootfs_data"
[    0.512608] SPI NOR MTD LOAD OK
[    0.516066] Bus Mode Reg after reset: 0x00020101, cnt=0
[    0.525144] libphy: jz_mii_bus: probed
[    0.529366] =======>gmacdev = 0x821b3000<================
[    0.534938] =========>gmacdev->MacBase = 0xb34b0000 DmaBase = 0xb34b1000
[    0.541986] Bus Mode Reg after reset: 0x00020101, cnt=0
[    0.549022] jz_mac jz_mac.0: JZ on-chip Ethernet MAC driver, Version 1.0
[    0.556240] STA : @@@@@@ rtusb init rt2870 --->
[    0.561152] usbcore: registered new interface driver rt2870
[    0.566902] i2c /dev entries driver
[    0.571770] jzmmc_v1.2 jzmmc_v1.2.0: vmmc regulator missing
[    0.577854] jzmmc_v1.2 jzmmc_v1.2.0: register success!
[    0.583283] jzmmc_v1.2 jzmmc_v1.2.1: vmmc regulator missing
[    0.589327] jzmmc_v1.2 jzmmc_v1.2.1: register success!
[    0.595081] ipip: IPv4 over IPv4 tunneling driver
[    0.600623] TCP: cubic registered
[    0.605076] NET: Registered protocol family 10
[    0.610516] NET: Registered protocol family 17
[    0.616305] input: gpio-keys as /devices/platform/gpio-keys/input/input0
[    0.623724] drivers/rtc/hctosys.c: unable to open rtc device (rtc0)
[    0.634802] VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
[    0.645949] devtmpfs: mounted
[    0.649374] Freeing unused kernel memory: 216K (8054a000 - 80580000)
[    0.779172] usb 1-1: new high-speed USB device number 2 using dwc2
[    1.096247] jffs2: notice: (451) jffs2_build_xattr_subsystem: complete building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0 orphan) found.
[    1.133709] 
[    1.133709] 
[    1.133709] === pAd = c0077000, size = 870056 ===
[    1.133709] 
[    1.150272] <-- RTMPAllocTxRxRingMemory, Status=0
[    1.155698] <-- RTMPAllocAdapterBlock, Status=0
[    1.177554] RTMP_COM_IoctlHandle():pAd->BulkOutEpAddr=0x8
[    1.186955] RTMP_COM_IoctlHandle():pAd->BulkOutEpAddr=0x4
[    1.196405] RTMP_COM_IoctlHandle():pAd->BulkOutEpAddr=0x5
[    1.205980] RTMP_COM_IoctlHandle():pAd->BulkOutEpAddr=0x6
[    1.211680] RTMP_COM_IoctlHandle():pAd->BulkOutEpAddr=0x7
[    1.217722] RTMP_COM_IoctlHandle():pAd->BulkOutEpAddr=0x9
[    1.223953] ==>WaitForAsicReady MAC_CSR0=0x76010500
[    1.229685] ==>WaitForAsicReady MAC_CSR0=0x76010500
[    1.235275] NVM is EFUSE
[    1.238381] Endpoint(8) is for In-band Command
[    1.243477] Endpoint(4) is for WMM0 AC0
[    1.247915] Endpoint(5) is for WMM0 AC1
[    1.252385] Endpoint(6) is for WMM0 AC2
[    1.256832] Endpoint(7) is for WMM0 AC3
[    1.261295] Endpoint(9) is for WMM1 AC0
[    1.265735] Endpoint(84) is for Data-In
[    1.270194] Endpoint(85) is for Command Rsp
[    1.523798] [resetd] GPIO undefined in /usr/sbin/resetd
[    2.691721] cfg80211: Calling CRDA to update world regulatory domain
[    2.890395] ==>WaitForAsicReady MAC_CSR0=0x76010500
[    2.895558] FW Version:0.1.00 Build:7640
[    2.895565] Build Time:201308201452____
[    2.895588] ILM Length = 46472(bytes)
[    2.895592] DLM Length = 0(bytes)
[    2.896507] Loading FW....
[    2.939139] #
[    2.946647] ==>WaitForAsicReady MAC_CSR0=0x76010500
[    2.958779] cfg_mode=9
[    2.958794] wmode_band_equal(): Band Equal!
[    2.961146] 1. Phy Mode = 14
[    2.961156] 2. Phy Mode = 14
[    2.966682] ERROR!!! MT7601 E2PROM: WRONG VERSION 0xc, should be 9
[    2.980153] 3. Phy Mode = 14
[    2.980164] AntCfgInit: primary/secondary ant 0/1
[    3.096620] MCS Set = ff 00 00 00 01
[    3.106796] <==== STA : rt28xx_init, Status=0
[    3.107379] 0x1300 = 00064300
[    3.107386] RTMPDrvOpen(1):Check if PDMA is idle!
[    3.107749] RTMPDrvOpen(2):Check if PDMA is idle!
[    9.040901] drivers/net/wireless/mt7601u/common/cmm_asic.c:2142 assert KeyIdx < 4failed
[    9.041240] drivers/net/wireless/mt7601u/common/cmm_asic.c:2142 assert KeyIdx < 4failed
[    9.805217] @@@@ tx-isp-probe ok(version H20221206a), compiler date=Dec  6 2022 @@@@@
[    9.850887] request spk en gpio 63 ok!
[    9.850899] jz_codec_register: probe() successful!
[    9.850989] cgu_set_rate, parent = 1392000000, rate = 2048000, n = 10875, reg val = 0x01002a7b
[    9.850998] cgu_enable,cgu_i2s_spk reg val = 0x21002a7b
[    9.851015] cgu_set_rate, parent = 1392000000, rate = 2048000, n = 10875, reg val = 0x01002a7b
[    9.851023] cgu_enable,cgu_i2s_mic reg val = 0x21002a7b
[   10.259318] dma dma0chan24: Channel 24 have been requested.(phy id 7,type 0x06 desc a282c000)
[   10.259610] dma dma0chan25: Channel 25 have been requested.(phy id 6,type 0x06 desc a147e000)
[   10.259932] dma dma0chan26: Channel 26 have been requested.(phy id 5,type 0x04 desc a2824000)
[   10.289497] Ingenic GPIO claim module (c) OpenIPC.org
[   11.299594] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   11.299615] i2c i2c-0: --I2C txabrt:
[   11.299624] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   11.299801] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   11.299810] i2c i2c-0: --I2C txabrt:
[   11.299818] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   11.299994] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   11.300041] i2c i2c-0: --I2C txabrt:
[   11.300050] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   11.300227] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   11.300236] i2c i2c-0: --I2C txabrt:
[   11.300245] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   11.300418] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   11.300430] i2c i2c-0: --I2C txabrt:
[   11.300439] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   11.300613] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   11.300622] i2c i2c-0: --I2C txabrt:
[   11.300630] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   11.300804] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   11.300815] i2c i2c-0: --I2C txabrt:
[   11.300824] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   11.301006] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   11.301018] i2c i2c-0: --I2C txabrt:
[   11.301027] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   11.301201] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   11.301210] i2c i2c-0: --I2C txabrt:
[   11.301218] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   11.301392] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   11.301403] i2c i2c-0: --I2C txabrt:
[   11.301412] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   11.301587] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[   11.301598] i2c i2c-0: --I2C txabrt:
[   11.301606] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[   11.353222] PeerBeaconAtJoinAction(): HT-CtrlChannel=13, CentralChannel=>13
[   11.353236] PeerBeaconAtJoinAction(): Set CentralChannel=13
[   11.391322] wait stable.[289][cgu_cim]
[   11.391338] probe ok ------->gc2053
[   11.469589] -----gc2053_detect: 1127 ret = 0, v = 0x20
[   11.470082] -----gc2053_detect: 1133 ret = 0, v = 0x53
[   11.470092] gc2053 chip found @ 0x37 (i2c0) version H20211111a
[   11.716897] gc2053 stream on
[   12.228365] Rcv Wcid(1) AddBAReq
[   12.228381] Start Seq = 00000000
root@convoy-t31:~# 
root@convoy-t31:~# 
root@convoy-t31:~# ifconfig
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:32 errors:0 dropped:0 overruns:0 frame:0
          TX packets:32 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2496 (2.4 KiB)  TX bytes:2496 (2.4 KiB)

wlan0     Link encap:Ethernet  HWaddr 2C:C3:E6:0A:75:95  
          inet addr:10.10.100.84  Bcast:10.10.100.255  Mask:255.255.255.0
          inet6 addr: fe80::2ec3:e6ff:fe0a:7595/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2118 errors:0 dropped:20 overruns:0 frame:0
          TX packets:40 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:470989 (459.9 KiB)  TX bytes:7376 (7.2 KiB)
root@convoy-t31:~# lsusb
Bus 001 Device 002: ID 148f:7601
Bus 001 Device 001: ID 1d6b:0002

**Comment by themactep** [comment]
Seems you have the driver loaded, you have the interface, even some networking. Is the IP address something you would expect from your dhcp? Disable autoload of wifi interface and run ifup -v wlan0 manually in console. Check for errors.
