### ISSUE TITLE
f2fs-tools are not present

### ISSUE THREAD

**Issue by southskies** [OpenIPC/firmware#953]
F2fs-tools is listed on the wiki [List of OpenIPC Buildroot packages](https://github.com/OpenIPC/wiki/blob/master/en/dev-buildroot-packages.md#:~:text=f2fs%2Dtools%201.14.0-,f2fs%2Dtools%201.15.0,-f2fs%2Dtools%201.15.0), but I cannot find the binaries. They are also listed in [firmware/blob/master/general/package/Config.in](https://github.com/OpenIPC/firmware/blob/master/general/package/Config.in#L14). 

![image](https://github.com/OpenIPC/firmware/assets/2459412/0a3dfe2e-ac4d-406c-8af2-6b94db838775)

```
cat /etc/os-release
NAME=Buildroot
VERSION=-gcac1781
ID=buildroot
VERSION_ID=2023.02.2
PRETTY_NAME="Buildroot 2023.02.2"
OPENIPC_VERSION=2.3.08.02
GITHUB_VERSION="master+cac1781, 2023-08-02"
BUILD_OPTION=ultimate
TIME_STAMP=1690991432
```

I'm I missing something or are they failing to build?

Thanks for all the hard work!

**Comment by widgetii** [comment]
I believe they simply don't fit into lite firmware due to its size, but nobody cares to add them into ultimate package yet.

As usual: feel free to make a PR

**Comment by southskies** [comment]
@widgetii I appreciate the quick reply. Thanks!
