### ISSUE TITLE
Cann't  set fps greater than 25 with GK7205V300 + IMX335

### ISSUE THREAD

**Issue by Lance0724** [OpenIPC/firmware#994]
GK7205V300 + IMX335 fps cannot be set to any value except 25 unexpectedly, 
otherwise the ground will not receive any packets

**Comment by widgetii** [comment]
According to SoC's datasheet:

<img width="694" alt="Screenshot 2023-09-16 at 08 47 54" src="https://github.com/OpenIPC/firmware/assets/6576495/01b89c46-71ed-457e-9861-cf1254ed8361">

What resolution do you use?

**Comment by Lance0724** [comment]
> According to SoC's datasheet:
> 
> <img alt="Screenshot 2023-09-16 at 08 47 54" width="694" src="https://user-images.githubusercontent.com/6576495/268431319-01b89c46-71ed-457e-9861-cf1254ed8361.png">
> What resolution do you use?

I only tried 1920X1080@fps30 and 1280X720@fps30, and it didn't work

video0：
  enabled: true
  bitrate: 8192
  codec: h265
  size: 1920x1080
  # fps:30
  rcMode: cbr
  gopSize: 0.2

**Comment by widgetii** [comment]
Make sure that your sensor also works on such fps (it could be figured out from the logs)

**Comment by Lance0724** [comment]
Where can I see the log? Is it standout after putty connection?

**Comment by Lance0724** [comment]
There are some new discoveries that when I enable the low latency mode, 
I can change the fps greater than 25 (e.g fps30, fps60), 
but there is no noticeable change in latency

**Comment by widgetii** [comment]
There is no way to have low latency in GK7205V300 + IMX335, the only board recommended is described in wiki

**Comment by Lance0724** [comment]
> There is no way to have low latency in GK7205V300 + IMX335, the only board recommended is described in wiki

Recommended board is IVG-G2S?  Right ?
